(() => {
const fullCasterSpellPoints = { 1: 4, 2: 6, 3: 14, 4: 17, 5: 27, 6: 32, 7: 38, 8: 44, 9: 57, 10: 64, 11: 73, 12: 73, 13: 83, 14: 83, 15: 94, 16: 94, 17: 107, 18: 114, 19: 123, 20: 133 };

window.DungeonContent.register("classes", "cleric", {
  name: "Test Cleric",
  className: "Cleric",
  classId: "cleric",
  classRole: "cleric",
  casterType: "full",
  role: "Level 1 Cleric",
  level: 1,
  xp: 0,
  hitDie: 8,
  maxHp: 11,
  abilityMods: { str: 1, dex: 1, con: 2, wis: 3 },
  baseAc: 10,
  attackBonus: 5,
  damage: { count: 1, sides: 6, bonus: 1, type: "bludgeoning", label: "1d6 + 1 bludgeoning" },
  initiativeBonus: 1,
  speedFeet: 30,
  armorProficiencies: ["light", "medium", "shield"],
  weaponProficiencies: ["simple"],
  spellcastingAbility: "wis",
  spellPointProgression: fullCasterSpellPoints,
  spellList: [
    "cure_wounds",
    "healing_word",
    "guiding_bolt",
    "bless",
    "bane",
    "command",
    "shield_of_faith",
    "sanctuary",
    "blindness-deafness",
    "calm-emotions",
    "enhance-ability",
    "prayer-of-healing",
    "gentle-repose",
    "lesser-restoration",
    "protection-from-poison",
    "warding-bond",
    "beacon-of-hope",
    "daylight",
    "revivify",
    "animate-dead",
    "bestow-curse",
    "remove-curse",
    "protection-from-energy",
    "banishment",
    "death-ward",
    "guardian-of-faith",
    "contagion",
    "dawn",
    "dispel-evil-and-good",
    "flame-strike",
    "insect-plague",
    "mass-cure-wounds",
    "greater-restoration",
    "raise-dead",
    "blade-barrier",
    "forbiddance",
    "harm",
    "heal",
    "heroes-feast",
    "true-seeing",
    "divine-word",
    "etherealness",
    "fire-storm",
    "regenerate",
    "resurrection",
    "symbol",
    "antimagic-field",
    "earthquake",
    "holy-aura",
    "mass-heal",
    "true-resurrection",
    "spiritual_weapon",
    "hold_person",
    "spirit_guardians",
    "dispel_magic",
    "mass_healing_word",
  ],
  cantripList: ["guidance", "light", "sacred-flame", "spare-the-dying", "resistance", "toll-the-dead"],
  spells: [],
  token: "C",
  classFeatures: [
    { level: 1, name: "Spellcasting", description: "You can shape class magic into prepared or known spells." },
    { level: 2, name: "Channel Divinity", description: "Call on divine power for sacred effects; uses increase at cleric levels 6 and 18 and refresh on a short rest." },
    { level: 8, name: "Blessed Strike", description: "Once on each of your turns, a weapon hit or damaging cantrip deals an extra 1d8 radiant damage." },
  ],
  abilities: [
    { id: "channelDivinity", name: "Channel Divinity", level: 2, refresh: "shortRest", uses: 1, usesByLevel: [{ level: 6, uses: 2 }, { level: 18, uses: 3 }], resource: "action", description: "Radiant divine burst against nearby enemies. Uses increase at cleric levels 6 and 18." },
  ],
  equipment: {
    mainHand: "mace",
    offHand: "shield",
    head: null,
    torso: "scale-mail",
    boots: null,
    cloak: null,
    bracers: null,
    gauntlets: null,
    ring1: null,
    ring2: null,
    amulet: null,
  },
  inventory: {
    money: { cp: 0, sp: 0, gp: 0 },
    items: ["mace", "shield", "scale-mail"],
  },
  startingGear: {
    equipment: { offHand: "shield" },
    inventory: ["shield"],
    steps: [
      {
        title: "Starting Weapon",
        message: "Choose your cleric weapon.",
        choices: [
          { value: "mace", label: "Mace", equipment: { mainHand: "mace" }, inventory: ["mace"] },
          { value: "warhammer", label: "Warhammer", equipment: { mainHand: "warhammer" }, inventory: ["warhammer"], requiresWeaponProficiency: "warhammer" },
        ],
      },
      {
        title: "Starting Armor",
        message: "Choose your cleric armor.",
        choices: [
          { value: "scale-mail", label: "Scale Mail", equipment: { torso: "scale-mail" }, inventory: ["scale-mail"] },
          { value: "leather", label: "Leather Armor", equipment: { torso: "leather" }, inventory: ["leather"] },
          { value: "chain-mail", label: "Chain Mail", equipment: { torso: "chain-mail" }, inventory: ["chain-mail"], requiresArmorProficiency: "chain-mail" },
        ],
      },
      {
        title: "Secondary Gear",
        message: "Choose your cleric's additional gear.",
        choices: [
          { value: "light-crossbow", label: "Light Crossbow and 20 Bolts", inventory: ["crossbow-light", "bolts-20"], quiver: "bolts-20" },
          {
            value: "simple",
            label: "Any simple weapon",
            select: { pool: "simpleWeapons", title: "Choose Simple Weapon", message: "Select a simple weapon.", label: "Weapon", slot: "" },
          },
        ],
      },
    ],
  },
});
})();
