(() => {
const fullCasterSpellPoints = { 1: 4, 2: 6, 3: 14, 4: 17, 5: 27, 6: 32, 7: 38, 8: 44, 9: 57, 10: 64, 11: 73, 12: 73, 13: 83, 14: 83, 15: 94, 16: 94, 17: 107, 18: 114, 19: 123, 20: 133 };

const wildShapeBeasts = [
  {
    id: "wildshape-wolf",
    name: "Wolf",
    cr: 0.25,
    size: "Medium",
    type: "Beast",
    ac: 13,
    hp: 11,
    speed: { walk: 40 },
    abilityScores: { str: 12, dex: 15, con: 12, int: 3, wis: 12, cha: 6 },
    skills: { perception: 3, stealth: 4 },
    senses: { passivePerception: 13 },
    traits: [
      { name: "Keen Hearing and Smell", description: "Advantage on Perception checks that rely on hearing or smell." },
      { name: "Pack Tactics", description: "Advantage on attack rolls if an ally is adjacent to the target." },
    ],
    actions: [
      {
        name: "Bite",
        type: "meleeWeaponAttack",
        attackBonus: 4,
        reach: 5,
        damage: "2d4 + 2",
        damageType: "piercing",
        effects: [{ type: "savingThrow", ability: "str", dc: 11, onFail: "Target is knocked prone." }],
      },
    ],
  },
  {
    id: "wildshape-panther",
    name: "Panther",
    cr: 0.25,
    size: "Medium",
    type: "Beast",
    ac: 12,
    hp: 13,
    speed: { walk: 50, climb: 40 },
    abilityScores: { str: 14, dex: 15, con: 10, int: 3, wis: 14, cha: 7 },
    skills: { perception: 4, stealth: 6 },
    senses: { passivePerception: 14 },
    traits: [
      { name: "Keen Smell", description: "Advantage on Perception checks that rely on smell." },
      { name: "Pounce", description: "After moving 20 feet straight toward a target, Claw can knock it prone." },
    ],
    actions: [
      { name: "Bite", type: "meleeWeaponAttack", attackBonus: 4, reach: 5, damage: "1d6 + 2", damageType: "piercing" },
      { name: "Claw", type: "meleeWeaponAttack", attackBonus: 4, reach: 5, damage: "1d4 + 2", damageType: "slashing" },
    ],
  },
  {
    id: "wildshape-giant-wolf-spider",
    name: "Giant Wolf Spider",
    cr: 0.25,
    size: "Medium",
    type: "Beast",
    ac: 13,
    hp: 11,
    speed: { walk: 40, climb: 40 },
    abilityScores: { str: 12, dex: 16, con: 13, int: 3, wis: 12, cha: 4 },
    skills: { perception: 3, stealth: 7 },
    senses: { blindsight: 10, darkvision: 60, passivePerception: 13 },
    traits: [
      { name: "Spider Climb", description: "Can climb difficult surfaces without an ability check." },
      { name: "Web Sense", description: "While touching a web, knows where other web-touching creatures are." },
      { name: "Web Walker", description: "Ignores movement restrictions caused by webbing." },
    ],
    actions: [
      {
        name: "Bite",
        type: "meleeWeaponAttack",
        attackBonus: 3,
        reach: 5,
        damage: "1d6 + 1",
        damageType: "piercing",
        effects: [{ type: "savingThrow", ability: "con", dc: 11, onFailDamage: "2d6", onFailDamageType: "poison", onSuccessDamage: "1d6", onSuccessDamageType: "poison" }],
      },
    ],
  },
  {
    id: "wildshape-black-bear",
    name: "Black Bear",
    cr: 0.5,
    size: "Medium",
    type: "Beast",
    ac: 11,
    hp: 19,
    speed: { walk: 40, climb: 30 },
    abilityScores: { str: 15, dex: 10, con: 14, int: 2, wis: 12, cha: 7 },
    skills: { perception: 3 },
    senses: { passivePerception: 13 },
    traits: [{ name: "Keen Smell", description: "Advantage on Perception checks that rely on smell." }],
    actions: [
      { name: "Multiattack", description: "The bear makes one Bite attack and one Claws attack." },
      { name: "Bite", type: "meleeWeaponAttack", attackBonus: 3, reach: 5, damage: "1d6 + 2", damageType: "piercing" },
      { name: "Claws", type: "meleeWeaponAttack", attackBonus: 3, reach: 5, damage: "2d4 + 2", damageType: "slashing" },
    ],
  },
  {
    id: "wildshape-ape",
    name: "Ape",
    cr: 0.5,
    size: "Medium",
    type: "Beast",
    ac: 12,
    hp: 19,
    speed: { walk: 30, climb: 30 },
    abilityScores: { str: 16, dex: 14, con: 14, int: 6, wis: 12, cha: 7 },
    skills: { athletics: 5, perception: 3 },
    senses: { passivePerception: 13 },
    traits: [],
    actions: [
      { name: "Multiattack", description: "The ape makes two Fist attacks." },
      { name: "Fist", type: "meleeWeaponAttack", attackBonus: 5, reach: 5, damage: "1d6 + 3", damageType: "bludgeoning" },
      { name: "Rock", type: "rangedWeaponAttack", attackBonus: 5, range: "25/50", damage: "1d6 + 3", damageType: "bludgeoning" },
    ],
  },
  {
    id: "wildshape-crocodile",
    name: "Crocodile",
    cr: 0.5,
    size: "Large",
    type: "Beast",
    ac: 12,
    hp: 19,
    speed: { walk: 20, swim: 30 },
    abilityScores: { str: 15, dex: 10, con: 13, int: 2, wis: 10, cha: 5 },
    skills: { stealth: 2 },
    senses: { passivePerception: 10 },
    traits: [{ name: "Hold Breath", description: "Can hold its breath for 15 minutes." }],
    actions: [
      { name: "Bite", type: "meleeWeaponAttack", attackBonus: 4, reach: 5, damage: "1d10 + 2", damageType: "piercing", effects: [{ type: "grapple", dc: 12, condition: "restrained" }] },
    ],
  },
  {
    id: "wildshape-brown-bear",
    name: "Brown Bear",
    cr: 1,
    size: "Large",
    type: "Beast",
    ac: 11,
    hp: 34,
    speed: { walk: 40, climb: 30 },
    abilityScores: { str: 19, dex: 10, con: 16, int: 2, wis: 13, cha: 7 },
    skills: { perception: 3 },
    senses: { passivePerception: 13 },
    traits: [{ name: "Keen Smell", description: "Advantage on Perception checks that rely on smell." }],
    actions: [
      { name: "Multiattack", description: "The bear makes one Bite attack and one Claws attack." },
      { name: "Bite", type: "meleeWeaponAttack", attackBonus: 5, reach: 5, damage: "1d8 + 4", damageType: "piercing" },
      { name: "Claws", type: "meleeWeaponAttack", attackBonus: 5, reach: 5, damage: "2d6 + 4", damageType: "slashing" },
    ],
  },
  {
    id: "wildshape-dire-wolf",
    name: "Dire Wolf",
    cr: 1,
    size: "Large",
    type: "Beast",
    ac: 14,
    hp: 37,
    speed: { walk: 50 },
    abilityScores: { str: 17, dex: 15, con: 15, int: 3, wis: 12, cha: 7 },
    skills: { perception: 3, stealth: 4 },
    senses: { passivePerception: 13 },
    traits: [
      { name: "Keen Hearing and Smell", description: "Advantage on Perception checks that rely on hearing or smell." },
      { name: "Pack Tactics", description: "Advantage on attack rolls if an ally is adjacent to the target." },
    ],
    actions: [
      { name: "Bite", type: "meleeWeaponAttack", attackBonus: 5, reach: 5, damage: "2d6 + 3", damageType: "piercing", effects: [{ type: "savingThrow", ability: "str", dc: 13, onFail: "Target is knocked prone." }] },
    ],
  },
  {
    id: "wildshape-giant-eagle",
    name: "Giant Eagle",
    cr: 1,
    size: "Large",
    type: "Beast",
    ac: 13,
    hp: 26,
    speed: { walk: 10, fly: 80 },
    abilityScores: { str: 16, dex: 17, con: 13, int: 8, wis: 14, cha: 10 },
    skills: { perception: 4 },
    senses: { passivePerception: 14 },
    traits: [{ name: "Keen Sight", description: "Advantage on Perception checks that rely on sight." }],
    actions: [
      { name: "Multiattack", description: "The eagle makes one Beak attack and one Talons attack." },
      { name: "Beak", type: "meleeWeaponAttack", attackBonus: 5, reach: 5, damage: "1d6 + 3", damageType: "piercing" },
      { name: "Talons", type: "meleeWeaponAttack", attackBonus: 5, reach: 5, damage: "2d6 + 3", damageType: "slashing" },
    ],
  },
];

const wildShapeUnlocks = [
  { druidLevel: 2, maxCr: 0.25, allowSwimSpeed: false, allowFlySpeed: false, beastIds: ["wildshape-wolf", "wildshape-panther", "wildshape-giant-wolf-spider"] },
  { druidLevel: 4, maxCr: 0.5, allowSwimSpeed: true, allowFlySpeed: false, beastIds: ["wildshape-black-bear", "wildshape-ape", "wildshape-crocodile"] },
  { druidLevel: 8, maxCr: 1, allowSwimSpeed: true, allowFlySpeed: true, beastIds: ["wildshape-brown-bear", "wildshape-dire-wolf", "wildshape-giant-eagle"] },
];

window.DungeonDruidWildShape = {
  beasts: wildShapeBeasts,
  unlocks: wildShapeUnlocks,
};

window.DungeonContent.register("classes", "druid", {
  name: "Greenwarden",
  className: "Druid",
  classId: "druid",
  classRole: "druid",
  casterType: "full",
  role: "Level 1 Druid",
  level: 1,
  xp: 0,
  hitDie: 8,
  maxHp: 10,
  abilityMods: { str: 0, dex: 2, con: 2, wis: 3 },
  baseAc: 10,
  attackBonus: 5,
  damage: { count: 1, sides: 6, bonus: 2, type: "bludgeoning", label: "1d6 + 2 bludgeoning" },
  initiativeBonus: 2,
  speedFeet: 30,
  armorProficiencies: ["light", "medium", "shield"],
  weaponProficiencies: ["club", "dagger", "dart", "javelin", "mace", "quarterstaff", "scimitar", "sickle", "sling", "spear"],
  spellcastingAbility: "wis",
  spellPointProgression: fullCasterSpellPoints,
  spellList: ["cure_wounds", "healing_word", "entangle", "faerie_fire", "thunderwave", "barkskin", "heat_metal", "moonbeam", "spike_growth", "call_lightning"],
  cantripList: ["guidance", "produce-flame", "thorn-whip", "thunderclap", "frostbite", "poison-spray", "primal-savagery", "resistance", "shillelagh"],
  spells: [],
  token: "D",
  classFeatures: [
    { level: 1, name: "Spellcasting", description: "You can shape class magic into prepared or known spells." },
    { level: 2, name: "Wild Shape", description: "Transform into beasts for exploration and combat utility." },
    { level: 18, name: "Beast Spells", description: "Cast many spells even while transformed by Wild Shape." },
  ],
  abilities: [
    { id: "wildShape", name: "Wild Shape", level: 2, refresh: "shortRest", uses: 2, resourcePool: "wildShape", resource: "bonusAction", description: "Transform into an unlocked beast form. Beast HP absorbs damage first; overflow carries over when you revert." },
  ],
  equipment: { mainHand: "quarterstaff", offHand: "shield", torso: "leather" },
  inventory: { money: { cp: 0, sp: 0, gp: 0 }, items: ["quarterstaff", "shield", "leather"] },
  startingGear: {
    equipment: { torso: "leather" },
    inventory: ["leather"],
    steps: [
      {
        title: "Shield or Weapon",
        message: "Choose your first druid item.",
        choices: [
          { value: "wooden-shield", label: "Wooden Shield", equipment: { offHand: "shield" }, inventory: ["shield"] },
          {
            value: "simple",
            label: "Any simple weapon",
            select: { pool: "simpleWeapons", title: "Choose Simple Weapon", message: "Select a simple weapon.", label: "Weapon", slot: "mainHand" },
          },
        ],
      },
      {
        title: "Melee Weapon",
        message: "Choose your druid melee weapon.",
        choices: [
          { value: "scimitar", label: "Scimitar", equipment: { mainHand: "scimitar" }, inventory: ["scimitar"] },
          {
            value: "simple-melee",
            label: "Any simple melee weapon",
            select: { pool: "simpleMeleeWeapons", title: "Choose Simple Melee Weapon", message: "Select a simple melee weapon.", label: "Weapon", slot: "mainHand" },
          },
        ],
      },
    ],
  },
});
})();
