(() => {
const fighterSubclassFeatureLevels = [3, 7, 10, 15, 18];
const thirdCasterSpellPoints = { 3: 4, 4: 6, 5: 6, 6: 6, 7: 14, 8: 14, 9: 14, 10: 17, 11: 17, 12: 17, 13: 27, 14: 27, 15: 27, 16: 32, 17: 32, 18: 32, 19: 38, 20: 38 };
const wizardCantrips = ["mage-hand", "blade-ward", "fire-bolt", "mind-sliver", "thunderclap", "chill-touch", "acid-splash", "booming-blade", "frostbite", "green-flame-blade", "ray-of-frost", "shocking-grasp", "toll-the-dead"];
const wizardCombatSpells = ["magic-missile", "shield", "burning-hands", "sleep", "grease", "scorching-ray", "web", "misty-step", "shatter", "lightning-bolt", "fireball", "haste"];
const superiorityUsesByLevel = [{ level: 7, uses: 5 }, { level: 15, uses: 6 }];
const arcaneShotUses = { refresh: "shortRest", uses: 2, resource: "bonusAction", resourcePool: "arcaneShot" };
const superiorityUse = { refresh: "shortRest", uses: 4, usesByLevel: superiorityUsesByLevel, resource: "bonusAction", resourcePool: "superiority" };
const runeUse = { refresh: "shortRest", uses: 1, usesByLevel: [{ level: 15, uses: 2 }], resource: "bonusAction" };

const battleMasterManeuvers = [
  { id: "maneuverAmbush", name: "Ambush", maneuver: "ambush", resource: "none", description: "Start fights with sudden battlefield awareness, adding your superiority die to initiative." },
  { id: "maneuverBaitAndSwitch", name: "Bait and Switch", maneuver: "baitAndSwitch", description: "Slip through the melee and cover an opening, raising your AC until your next turn." },
  { id: "maneuverBrace", name: "Brace", maneuver: "brace", resource: "reaction", description: "When an enemy steps into your reach, punish the approach with a quick reaction strike." },
  { id: "maneuverCommandersStrike", name: "Commander's Strike", maneuver: "commandersStrike", description: "Turn your tactical eye toward an ally, setting them up to land a stronger strike." },
  { id: "maneuverCommandingPresence", name: "Commanding Presence", maneuver: "commandingPresence", description: "Bring military confidence to tense talks, boosting social checks where presence matters." },
  { id: "maneuverDisarming", name: "Disarming Attack", maneuver: "disarming", description: "Strike at an enemy's weapon arm, adding damage and reducing their next attack threat." },
  { id: "maneuverDistracting", name: "Distracting Strike", maneuver: "distracting", description: "Hit in a way that opens the target's guard, making it easier for allies to follow up." },
  { id: "maneuverEvasiveFootwork", name: "Evasive Footwork", maneuver: "evasiveFootwork", description: "Move with careful guard and sharp footwork, briefly increasing your AC." },
  { id: "maneuverFeinting", name: "Feinting Attack", maneuver: "feinting", description: "Fake out your target, gaining advantage and extra damage on your next weapon hit." },
  { id: "maneuverGoading", name: "Goading Attack", maneuver: "goading", description: "Make yourself impossible to ignore, damaging a foe and drawing their focus toward you." },
  { id: "maneuverGrappling", name: "Grappling Strike", maneuver: "grappling", description: "Drive into close quarters after a hit, adding damage and briefly pinning the enemy down." },
  { id: "maneuverLunging", name: "Lunging Attack", maneuver: "lunging", description: "Commit to a long-reaching thrust, adding mobility and extra damage to your next hit." },
  { id: "maneuverManeuvering", name: "Maneuvering Attack", maneuver: "maneuvering", description: "Strike while directing an ally to a better position, adding damage and helping them move." },
  { id: "maneuverMenacing", name: "Menacing Attack", maneuver: "menacing", description: "Put real fear behind the blow, adding damage and frightening the target." },
  { id: "maneuverParry", name: "Parry", maneuver: "parry", resource: "reaction", description: "Catch or turn aside a melee hit, reducing the damage with practiced defense." },
  { id: "maneuverPrecision", name: "Precision Attack", maneuver: "precision", description: "Steady the decisive swing or shot, adding a superiority die to your next attack roll." },
  { id: "maneuverPushing", name: "Pushing Attack", maneuver: "pushing", description: "Hit with enough force to disrupt the enemy's footing, adding damage and hindering movement." },
  { id: "maneuverQuickToss", name: "Quick Toss", maneuver: "quickToss", description: "Snap off a fast thrown or off-hand style attack without giving up your main pressure." },
  { id: "maneuverRally", name: "Rally", maneuver: "rally", description: "Shout a sharp command that steadies an ally and grants them temporary hit points." },
  { id: "maneuverRiposte", name: "Riposte", maneuver: "riposte", resource: "reaction", description: "When a melee attacker misses you, answer immediately with a punishing counterattack." },
  { id: "maneuverSweeping", name: "Sweeping Attack", maneuver: "sweeping", description: "Carry your momentum through one enemy into another, splashing damage to a nearby foe." },
  { id: "maneuverTacticalAssessment", name: "Tactical Assessment", maneuver: "tacticalAssessment", description: "Read a scene like a commander, boosting checks that reward planning, insight, or study." },
  { id: "maneuverTrip", name: "Trip Attack", maneuver: "trip", description: "Hook, slam, or sweep the target down, adding damage and knocking them prone." },
].map((maneuver) => ({ ...superiorityUse, ...maneuver }));

const arcaneShotOptions = [
  { id: "arcaneShotBanishing", name: "Banishing Arrow", shot: "banishing", description: "Wrap an arrow in banishing magic, dealing damage and briefly removing a dangerous foe from the fight." },
  { id: "arcaneShotBeguiling", name: "Beguiling Arrow", shot: "beguiling", description: "Thread fey charm through your shot, hurting the target and clouding their judgment." },
  { id: "arcaneShotBursting", name: "Bursting Arrow", shot: "bursting", description: "Pack explosive force into an arrow so the hit erupts into nearby splash damage." },
  { id: "arcaneShotEnfeebling", name: "Enfeebling Arrow", shot: "enfeebling", description: "Drain strength from the target with necrotic magic, making their weapon blows less dangerous." },
  { id: "arcaneShotGrasping", name: "Grasping Arrow", shot: "grasping", description: "Snare an enemy in conjured brambles, adding poison damage and slowing their escape." },
  { id: "arcaneShotPiercing", name: "Piercing Arrow", shot: "piercing", description: "Loose an arrow that becomes spectral force, ideal when you want a shot to punch through defenses." },
  { id: "arcaneShotSeeking", name: "Seeking Arrow", shot: "seeking", description: "Send a guided arrow after your chosen foe, helping your next shot find its mark." },
  { id: "arcaneShotShadow", name: "Shadow Arrow", shot: "shadow", description: "Lace the arrow with shadow magic, damaging the target and disrupting their aim." },
].map((shot) => ({ ...arcaneShotUses, ...shot }));

const runeKnightRunes = [
  { id: "cloudRune", name: "Cloud Rune", rune: "cloud", resource: "reaction", description: "Call on cloud-giant trickery to twist a threatening hit away from its mark." },
  { id: "fireRune", name: "Fire Rune", rune: "fire", description: "Brand your next weapon hit with fiery chains that burn and briefly restrain the target." },
  { id: "frostRune", name: "Frost Rune", rune: "frost", description: "Harden yourself with frost-giant endurance, improving tough checks and saving throws." },
  { id: "stoneRune", name: "Stone Rune", rune: "stone", resource: "reaction", description: "Invoke stone-giant dream magic to daze a nearby foe at the edge of battle." },
  { id: "hillRune", name: "Hill Rune", rune: "hill", level: 7, description: "Take on hill-giant toughness, resisting weapon punishment and poison." },
  { id: "stormRune", name: "Storm Rune", rune: "storm", level: 7, description: "Open your sight to storm-giant prophecy, fighting with uncanny advantage." },
].map((rune) => ({ ...runeUse, ...rune, level: rune.level ?? 3 }));

const fighterSubclasses = [
  {
    id: "arcane-archer",
    name: "Arcane Archer",
    source: "Xanathar's Guide to Everything",
    summary: "A magical archer who turns chosen shots into control, burst damage, and battlefield tricks.",
    gameplayGuide: [
      "You know a small list of Arcane Shot options. Choose the ones that match how you want your arrows to control fights.",
      "Arcane Shots are spent from a shared pool and come back on a short or long rest. Use them on important bow hits, not every attack.",
      "Later levels add more known shot options, improve your magic archery, and eventually restore one shot at the start of combat if you are empty.",
    ],
    featureNamesByLevel: {
      3: ["Arcane Archer Lore", "Arcane Shot"],
      7: ["Magic Arrow", "Curving Shot"],
      10: ["Additional Arcane Shot"],
      15: ["Ever-Ready Shot"],
      18: ["Arcane Shot Improvement"],
    },
    features: [
      { level: 3, name: "Arcane Archer Lore", description: "Blend archery with old magical study, choosing Arcana or Nature training and a small lore cantrip." },
      { level: 3, name: "Arcane Shot", description: "Learn special enchanted arrows that turn hits into banishment, charms, shadow, force, or other battlefield effects." },
      { level: 7, name: "Magic Arrow", description: "Your archery carries magical force, helping your arrows matter against supernatural enemies." },
      { level: 7, name: "Curving Shot", description: "Your magic can bend a missed arrow toward a better line, giving your archery a forgiving, trick-shot feel." },
      { level: 15, name: "Ever-Ready Shot", description: "You never enter a fight completely empty-handed; if your Arcane Shots are spent, one returns as combat begins." },
    ],
    optionCounts: { arcaneShots: [{ level: 3, count: 2 }, { level: 7, count: 3 }, { level: 10, count: 4 }, { level: 15, count: 5 }, { level: 18, count: 6 }] },
    arcaneShotOptions,
    abilities: arcaneShotOptions,
  },
  {
    id: "banneret",
    name: "Banneret",
    source: "Sword Coast Adventurer's Guide",
    summary: "A battlefield leader who turns personal grit into healing, courage, and openings for allies.",
    gameplayGuide: [
      "This subclass has few extra buttons because most of its power rides on normal fighter features.",
      "Second Wind becomes party support: when you heal yourself, nearby allies also recover.",
      "Action Surge later inspires an ally to hit harder, and Persuasion expertise makes this fighter the party's commander in conversations.",
    ],
    featureNamesByLevel: {
      3: ["Rallying Cry"],
      7: ["Royal Envoy"],
      10: ["Inspiring Surge"],
      15: ["Bulwark"],
      18: ["Inspiring Surge Improvement"],
    },
    features: [
      { level: 3, name: "Rallying Cry", description: "When you catch your breath with Second Wind, nearby allies also recover from your shouted encouragement." },
      { level: 7, name: "Royal Envoy", description: "You become a practiced commander and negotiator, gaining strong Persuasion support." },
      { level: 10, name: "Inspiring Surge", description: "When you push yourself with Action Surge, an ally is inspired to strike harder." },
      { level: 15, name: "Bulwark", description: "Your stubborn resolve can steady companions against danger, making you feel like the party's defensive anchor." },
    ],
  },
  {
    id: "battle-master",
    name: "Battle Master",
    source: "Player's Handbook",
    summary: "A tactical weapon master who spends superiority dice on precise attacks, counters, and ally support.",
    gameplayGuide: [
      "You have a pool of superiority dice that returns on a short or long rest.",
      "Most maneuvers spend one superiority die to enhance an attack, protect yourself, command an ally, or control an enemy.",
      "Some maneuvers are buttons you press before attacking, while reaction maneuvers appear as prompts when the right enemy action happens.",
      "At higher levels you learn more maneuvers, your dice get stronger, and Relentless gives one die back when combat starts if you are empty.",
    ],
    featureNamesByLevel: {
      3: ["Combat Superiority", "Student of War"],
      7: ["Know Your Enemy"],
      10: ["Improved Combat Superiority"],
      15: ["Relentless"],
      18: ["Improved Combat Superiority"],
    },
    features: [
      { level: 3, name: "Combat Superiority", description: "Gain superiority dice and spend them on chosen maneuvers that add damage, defense, control, or command." },
      { level: 3, name: "Student of War", description: "Pick up an artisan's tool, reflecting a soldier's practical craft and battlefield discipline." },
      { level: 7, name: "Know Your Enemy", description: "Study a creature like a tactician, learning how your strengths compare before steel is drawn." },
      { level: 15, name: "Relentless", description: "When a fight begins and your tactical reserves are empty, you recover one superiority die." },
    ],
    optionCounts: { maneuvers: [{ level: 3, count: 3 }, { level: 7, count: 5 }, { level: 10, count: 7 }, { level: 15, count: 9 }] },
    maneuverOptions: battleMasterManeuvers,
    abilities: battleMasterManeuvers,
  },
  {
    id: "cavalier",
    name: "Cavalier",
    source: "Xanathar's Guide to Everything",
    summary: "A defender who locks enemies down, protects nearby allies, and punishes foes who ignore you.",
    gameplayGuide: [
      "Play near enemies and allies. The Cavalier wants to hold the front line, mark threats, and punish movement.",
      "Unwavering Mark pressures a chosen enemy and makes your next hit against them stronger.",
      "Warding Maneuver is a reaction-style defensive tool for blunting attacks, while later features reward moving into a charge before striking.",
      "This version focuses on the Cavalier as a protective front-line defender: mark threats, guard allies, and punish enemies who try to slip past you.",
    ],
    featureNamesByLevel: {
      3: ["Bonus Proficiency", "Born to the Saddle", "Unwavering Mark"],
      7: ["Warding Maneuver"],
      10: ["Hold the Line"],
      15: ["Ferocious Charger"],
      18: ["Vigilant Defender"],
    },
    features: [
      { level: 3, name: "Bonus Proficiency", description: "Gain training that suits a noble rider or front-line protector." },
      { level: 3, name: "Born to the Saddle", description: "You are at home in the saddle, harder to unseat and quicker to recover when mounted." },
      { level: 3, name: "Unwavering Mark", description: "Mark a target with relentless pressure, making your next strike against them hit harder." },
      { level: 7, name: "Warding Maneuver", description: "Throw your shield, weapon, or body into danger to blunt an incoming attack." },
      { level: 10, name: "Hold the Line", description: "Enemies that try to slip past you risk being stopped in their tracks." },
      { level: 15, name: "Ferocious Charger", description: "Build momentum across the battlefield and crash into a foe with a punishing hit." },
    ],
    abilities: [
      { id: "unwaveringMark", name: "Unwavering Mark", level: 3, refresh: "longRest", uses: 1, resource: "bonusAction", description: "Challenge your current target and make your next weapon hit against them more punishing." },
      { id: "wardingManeuver", name: "Warding Maneuver", level: 7, refresh: "longRest", uses: 1, resource: "reaction", description: "Raise a last-second defense that improves AC and softens weapon damage." },
      { id: "ferociousCharger", name: "Ferocious Charger", level: 15, refresh: "turn", uses: 1, resource: "bonusAction", description: "After moving, slam into your enemy with extra damage and a chance to slow their advance." },
    ],
  },
  {
    id: "champion",
    name: "Champion",
    source: "Player's Handbook",
    summary: "A straightforward martial powerhouse with better critical hits, athletic talent, and steady survival.",
    gameplayGuide: [
      "Champion is the simplest fighter archetype: most benefits are always on, with very little resource tracking.",
      "Your weapon attacks crit more often, then even more often at higher level.",
      "Remarkable Athlete quietly improves physical checks, Additional Fighting Style adds another combat specialty, and Survivor heals you each turn while badly hurt.",
    ],
    featureNamesByLevel: {
      3: ["Improved Critical"],
      7: ["Remarkable Athlete"],
      10: ["Additional Fighting Style"],
      15: ["Superior Critical"],
      18: ["Survivor"],
    },
    features: [
      { level: 3, name: "Improved Critical", description: "Your weapon attacks land devastating critical hits more often, starting on a 19 or 20." },
      { level: 7, name: "Remarkable Athlete", description: "Your raw physical training helps with athletic movement, quick reactions, and feats of strength." },
      { level: 10, name: "Additional Fighting Style", description: "Broaden your combat training with another fighting style." },
      { level: 15, name: "Superior Critical", description: "Your killing edge sharpens further, letting weapon attacks crit on an 18, 19, or 20." },
      { level: 18, name: "Survivor", description: "When badly hurt, you keep fighting through pain and recover hit points at the start of your turns." },
    ],
  },
  {
    id: "echo-knight",
    name: "Echo Knight",
    source: "Explorer's Guide to Wildemount",
    summary: "A strange martial specialist who fights beside a fading echo of possible timelines.",
    gameplayGuide: [
      "Your echo features give you mobility, reach-like pressure, extra attacks, and reaction defense instead of a fully separate token.",
      "Manifest Echo helps you reposition and threaten farther for the turn. Unleash Incarnation spends limited uses for an extra melee attack.",
      "Shadow Martyr can appear as a defensive reaction, Reclaim Potential turns echo energy into temporary HP, and Legion of One helps restore echo offense at combat start.",
    ],
    featureNamesByLevel: {
      3: ["Manifest Echo", "Unleash Incarnation"],
      7: ["Echo Avatar"],
      10: ["Shadow Martyr"],
      15: ["Reclaim Potential"],
      18: ["Legion of One"],
    },
    features: [
      { level: 3, name: "Manifest Echo", description: "Create a ghostly echo of yourself that extends your reach and lets you fight from unexpected angles." },
      { level: 3, name: "Unleash Incarnation", description: "Strike through your echo for an extra melee attack when you need a burst of pressure." },
      { level: 7, name: "Echo Avatar", description: "Send your echo ahead as a scouting presence, perfect for peeking into danger before you commit." },
      { level: 10, name: "Shadow Martyr", description: "Throw your echo into the path of an incoming attack to shield someone from harm." },
      { level: 15, name: "Reclaim Potential", description: "Pull fading echo energy back into yourself as temporary hit points." },
      { level: 18, name: "Legion of One", description: "Your echo becomes easier to call on, keeping your extra-attack potential ready at the start of battle." },
    ],
    abilities: [
      { id: "manifestEcho", name: "Manifest Echo", level: 3, refresh: "turn", uses: 1, resource: "bonusAction", description: "Call up your echo for the turn, gaining extra movement and extended melee reach." },
      { id: "unleashIncarnation", name: "Unleash Incarnation", level: 3, refresh: "longRest", uses: 1, resource: "bonusAction", description: "Attack through your echo for an extra melee strike against your current target." },
      { id: "shadowMartyr", name: "Shadow Martyr", level: 10, refresh: "shortRest", uses: 1, resource: "reaction", description: "Sacrifice your echo's position to blunt a dangerous incoming attack." },
      { id: "reclaimPotential", name: "Reclaim Potential", level: 15, refresh: "longRest", uses: 1, resource: "bonusAction", description: "Draw power from your fading echo and gain temporary hit points." },
    ],
  },
  {
    id: "eldritch-knight",
    name: "Eldritch Knight",
    source: "Player's Handbook",
    summary: "A weapon fighter who backs steel with wizard cantrips, protective magic, and arcane mobility.",
    gameplayGuide: [
      "You are still a fighter first, but you also learn wizard cantrips and spells using Intelligence.",
      "Use cantrips and spells for ranged pressure, defense, area damage, and control when a plain weapon attack is not the best answer.",
      "Later features reward mixing blade and spell: weapon hits can set up magic, and Action Surge gains a teleport-like repositioning burst.",
      "Weapon Bond is treated as flavor for your bonded fighting style; your active tools are spellcasting, defensive magic, and arcane movement.",
    ],
    casterType: "third",
    spellcastingAbility: "int",
    spellPointProgression: thirdCasterSpellPoints,
    cantripList: wizardCantrips,
    spellList: wizardCombatSpells,
    featureNamesByLevel: {
      3: ["Spellcasting", "Weapon Bond"],
      7: ["War Magic"],
      10: ["Eldritch Strike"],
      15: ["Arcane Charge"],
      18: ["Improved War Magic"],
    },
    features: [
      { level: 3, name: "Spellcasting", description: "Learn wizard cantrips and combat spells, giving your fighter ranged magic, defenses, and area control." },
      { level: 3, name: "Weapon Bond", description: "Bind yourself to favored weapons so they feel like extensions of your own body." },
      { level: 7, name: "War Magic", description: "Blend spell and steel in the same battle rhythm, using cantrips without giving up martial pressure." },
      { level: 10, name: "Eldritch Strike", description: "Your weapon hits leave enemies vulnerable to your next spell, rewarding a strike-then-cast style." },
      { level: 15, name: "Arcane Charge", description: "When you surge into action, teleport across the battlefield in a flash of arcane force." },
    ],
  },
  {
    id: "psi-warrior",
    name: "Psi Warrior",
    source: "Tasha's Cauldron of Everything",
    summary: "A psionic fighter who spends mental energy on forceful strikes, shields, and sudden movement.",
    gameplayGuide: [
      "You have a psionic energy pool that fuels multiple powers and returns on a long rest.",
      "Psionic Strike spends energy to add force damage to a weapon hit. Protective Field spends energy as a reaction to reduce incoming damage.",
      "Psi-Powered Leap gives short-rest mobility, Guarded Mind protects against psychic harm, and Bulwark of Force later shields active allies with bonus AC.",
    ],
    featureNamesByLevel: {
      3: ["Psionic Power"],
      7: ["Telekinetic Adept"],
      10: ["Guarded Mind"],
      15: ["Bulwark of Force"],
      18: ["Telekinetic Master"],
    },
    features: [
      { level: 3, name: "Psionic Power", description: "Use psionic energy to empower weapon hits, shield allies, and keep mental reserves flowing." },
      { level: 7, name: "Telekinetic Adept", description: "Move with telekinetic lift and add extra force to your battlefield control." },
      { level: 10, name: "Guarded Mind", description: "Harden your thoughts against psychic harm and mental assault." },
      { level: 15, name: "Bulwark of Force", description: "Project a protective field that makes your active allies harder to hit." },
      { level: 18, name: "Telekinetic Master", description: "Enter a heightened telekinetic state, turning your attacks into crushing force." },
    ],
    abilities: [
      { id: "psionicStrike", name: "Psionic Strike", level: 3, refresh: "longRest", uses: 4, usesByLevel: [{ level: 5, uses: 6 }, { level: 9, uses: 8 }, { level: 13, uses: 10 }, { level: 17, uses: 12 }], resource: "bonusAction", resourcePool: "psionicEnergy", description: "Charge your next weapon hit with invisible force for extra damage." },
      { id: "protectiveField", name: "Protective Field", level: 3, refresh: "longRest", uses: 4, usesByLevel: [{ level: 5, uses: 6 }, { level: 9, uses: 8 }, { level: 13, uses: 10 }, { level: 17, uses: 12 }], resource: "reaction", resourcePool: "psionicEnergy", description: "Throw up a telekinetic shield to reduce incoming damage." },
      { id: "psiPoweredLeap", name: "Psi-Powered Leap", level: 7, refresh: "shortRest", uses: 1, resource: "bonusAction", description: "Lift yourself with psionic force, doubling your speed for the turn." },
      { id: "bulwarkOfForce", name: "Bulwark of Force", level: 15, refresh: "longRest", uses: 1, resource: "bonusAction", description: "Surround active heroes with a force barrier that temporarily improves AC." },
      { id: "telekineticMaster", name: "Telekinetic Master", level: 18, refresh: "longRest", uses: 1, resource: "action", description: "Enter a supreme telekinetic focus, adding force damage and keeping your weapon rhythm fast." },
    ],
  },
  {
    id: "rune-knight",
    name: "Rune Knight",
    source: "Tasha's Cauldron of Everything",
    summary: "A giant-taught warrior who carves runes, grows in battle, and invokes ancient giant magic.",
    gameplayGuide: [
      "You know a set of runes. Each rune represents passive giant lore plus an invoked combat effect.",
      "Rune invocations are limited uses and return on a short or long rest. Choose runes for the kind of defense, control, or damage you want.",
      "Giant's Might is separate from rune invocations: use it as a bonus action to grow in power and add weapon damage for the fight.",
      "Runic Shield is a reaction defense, while Master of Runes later lets your chosen runes be invoked more often.",
    ],
    featureNamesByLevel: {
      3: ["Bonus Proficiencies", "Rune Carver", "Giant's Might"],
      7: ["Runic Shield"],
      10: ["Great Stature"],
      15: ["Master of Runes"],
      18: ["Runic Juggernaut"],
    },
    features: [
      { level: 3, name: "Bonus Proficiencies", description: "Learn smith's tools and the Giant language, grounding your magic in runecarving tradition." },
      { level: 3, name: "Rune Carver", description: "Choose giant runes that grant passive flavor and powerful combat invocations." },
      { level: 3, name: "Giant's Might", description: "Grow with giant power, becoming harder to ignore and hitting harder with weapons." },
      { level: 7, name: "Runic Shield", description: "Flash a protective rune to disrupt a dangerous attack against you or an ally." },
      { level: 10, name: "Great Stature", description: "Your giant power deepens, making Giant's Might hit harder." },
      { level: 15, name: "Master of Runes", description: "You can draw on your carved runes more often between rests." },
      { level: 18, name: "Runic Juggernaut", description: "Your giant transformation becomes massive and terrifying, adding reach-like pressure and greater damage." },
    ],
    optionCounts: { runes: [{ level: 3, count: 2 }, { level: 7, count: 3 }, { level: 10, count: 4 }, { level: 15, count: 5 }] },
    runeOptions: runeKnightRunes,
    abilities: [
      { id: "giantsMight", name: "Giant's Might", level: 3, refresh: "longRest", uses: 2, usesByLevel: [{ level: 5, uses: 3 }, { level: 9, uses: 4 }, { level: 13, uses: 5 }, { level: 17, uses: 6 }], resource: "bonusAction", description: "Grow with giant power for the fight, adding extra weapon damage." },
      { id: "runicShield", name: "Runic Shield", level: 7, refresh: "longRest", uses: 2, usesByLevel: [{ level: 5, uses: 3 }, { level: 9, uses: 4 }, { level: 13, uses: 5 }, { level: 17, uses: 6 }], resource: "reaction", description: "Force a threatening attack to falter with a sudden flash of rune magic." },
      ...runeKnightRunes,
    ],
  },
  {
    id: "samurai",
    name: "Samurai",
    source: "Xanathar's Guide to Everything",
    summary: "A disciplined warrior who spends resolve for reliable advantage, durability, and sudden extra strikes.",
    gameplayGuide: [
      "Fighting Spirit is your core resource: spend it as a bonus action for attack advantage and temporary HP.",
      "Use Fighting Spirit before an important attack turn, especially when you want reliable hits or need a little durability.",
      "Tireless Spirit restores one use at combat start if you are empty, Rapid Strike turns advantage into another attack, and Strength Before Death gives one last surge when you would fall.",
    ],
    featureNamesByLevel: {
      3: ["Bonus Proficiency", "Fighting Spirit"],
      7: ["Elegant Courtier"],
      10: ["Tireless Spirit"],
      15: ["Rapid Strike"],
      18: ["Strength Before Death"],
    },
    features: [
      { level: 3, name: "Bonus Proficiency", description: "Gain a refined social or courtly skill to match your disciplined bearing." },
      { level: 3, name: "Fighting Spirit", description: "Focus your resolve as a bonus action, gaining advantage on attacks and temporary hit points." },
      { level: 7, name: "Elegant Courtier", description: "Your discipline sharpens both willpower and diplomacy, supporting Wisdom saves and Persuasion." },
      { level: 10, name: "Tireless Spirit", description: "If battle begins and your resolve is spent, you recover one use of Fighting Spirit." },
      { level: 15, name: "Rapid Strike", description: "While Fighting Spirit gives you advantage, trade that opening for one more weapon attack." },
      { level: 18, name: "Strength Before Death", description: "When you would fall, sheer will lets you seize one last chance to act before death takes hold." },
    ],
    abilities: [
      { id: "fightingSpirit", name: "Fighting Spirit", level: 3, refresh: "longRest", uses: 3, resource: "bonusAction", description: "Center yourself in battle, gaining attack advantage this turn and temporary hit points." },
      { id: "rapidStrike", name: "Rapid Strike", level: 15, refresh: "turn", uses: 1, resource: "bonusAction", description: "While Fighting Spirit is active, make one extra attack against your current target." },
      { id: "strengthBeforeDeath", name: "Strength Before Death", level: 18, refresh: "longRest", uses: 1, resource: "reaction", description: "When damage would drop you to 0 HP, your resolve buys you one final surge." },
    ],
  },
];

window.DungeonContent.register("classes", "fighter", {
  name: "Mira Vale",
  className: "Fighter",
  classId: "fighter",
  classRole: "fighter",
  casterType: "none",
  role: "Level 1 Fighter",
  level: 1,
  xp: 0,
  hitDie: 10,
  maxHp: 14,
  abilityMods: { str: 3, dex: 2 },
  baseAc: 10,
  attackBonus: 5,
  damage: { count: 1, sides: 4, bonus: 3, type: "bludgeoning", label: "1d4 + 3 bludgeoning" },
  initiativeBonus: 2,
  speedFeet: 30,
  armorProficiencies: ["light", "medium", "heavy", "shield"],
  weaponProficiencies: ["simple", "martial"],
  token: "M",
  classFeatures: [
    { level: 1, name: "Second Wind", description: "Draw on your reserves to restore your own hit points." },
    { level: 2, name: "Action Surge", description: "Push beyond normal limits to take an additional action." },
    { level: 3, name: "Martial Archetype", description: "Choose a fighter subclass and gain its first archetype features." },
    { level: 5, name: "Extra Attack", description: "Attack more than once when you take the Attack action." },
    { level: 9, name: "Indomitable", description: "Reroll a failed saving throw through sheer resolve." },
  ],
  subclassFeatureLevels: fighterSubclassFeatureLevels,
  subclasses: fighterSubclasses,
  abilities: [
    {
      id: "secondWind",
      name: "Second Wind",
      level: 1,
      refresh: "shortRest",
      uses: 1,
      resource: "bonusAction",
      description: "Catch your breath in the middle of battle and recover 1d10 + fighter level hit points.",
    },
    {
      id: "actionSurge",
      name: "Action Surge",
      level: 2,
      refresh: "shortRest",
      uses: 1,
      usesByLevel: [
        { level: 17, uses: 2 },
      ],
      resource: "none",
      description: "Push past normal limits and regain your action for another attack, spell, dash, or tactical move.",
    },
  ],
  equipment: {
    mainHand: "longsword",
    offHand: null,
    head: null,
    torso: "chain-mail",
    boots: null,
    cloak: null,
    bracers: null,
    gauntlets: null,
    ring1: null,
    ring2: null,
    amulet: null,
  },
  inventory: {
    money: { cp: 0, sp: 0, gp: 0 },
    items: [
      "longsword",
      "chain-mail",
    ],
  },
  startingGear: {
    armorChoices: [
      {
        value: "chain-mail",
        label: "Chain Mail",
        equipment: { torso: "chain-mail" },
        inventory: ["chain-mail"],
      },
      {
        value: "leather-longbow",
        label: "Leather Armor, Longbow, and 20 Arrows",
        equipment: { torso: "leather", quiver: "arrows-20" },
        inventory: ["leather", "longbow", "arrows-20"],
      },
    ],
    weaponChoices: [
      {
        value: "weapon-shield",
        label: "One martial weapon and a shield",
        equipment: { offHand: "shield" },
      },
      {
        value: "two-weapons",
        label: "Two martial weapons",
      },
    ],
    martialWeapons: [
      "battleaxe",
      "flail",
      "glaive",
      "greataxe",
      "greatsword",
      "halberd",
      "lance",
      "longsword",
      "maul",
      "morningstar",
      "pike",
      "rapier",
      "scimitar",
      "shortsword",
      "trident",
      "war-pick",
      "warhammer",
      "whip",
      "blowgun",
      "crossbow-hand",
      "crossbow-heavy",
      "longbow",
    ],
    secondaryChoices: [
      {
        value: "light-crossbow",
        label: "Light Crossbow and 20 Bolts",
        inventory: ["crossbow-light", "bolts-20"],
        quiver: "bolts-20",
      },
      {
        value: "handaxes",
        label: "Two Handaxes",
        inventory: ["handaxe", "handaxe"],
      },
    ],
  },
});
})();
