(() => {
window.DungeonContent.register("classes", "sidekick-warrior", {
  hidden: true,
  sidekickOnly: true,
  name: "Warrior Sidekick",
  className: "Warrior Sidekick",
  classId: "sidekick-warrior",
  classRole: "warrior",
  casterType: "none",
  role: "Level 1 Warrior Sidekick",
  level: 1,
  xp: 0,
  hitDie: 10,
  maxHp: 10,
  abilityMods: { str: 2, dex: 2, con: 2 },
  baseAc: 10,
  attackBonus: 4,
  damage: { count: 1, sides: 6, bonus: 2, type: "piercing", label: "1d6 + 2 piercing" },
  initiativeBonus: 2,
  speedFeet: 30,
  armorProficiencies: ["light", "medium", "heavy"],
  weaponProficiencies: [],
  savingThrowProficiencies: ["con"],
  skillProficiencies: ["perception", "survival"],
  token: "S",
  classFeatures: [
    { level: 1, name: "Bonus Proficiencies", description: "The sidekick gains combat, save, and skill training." },
    { level: 1, name: "Martial Role", description: "Attacker grants +2 to attack rolls; Defender protects nearby allies." },
    { level: 2, name: "Second Wind", description: "Regain 1d10 + sidekick level hit points as a bonus action." },
    { level: 3, name: "Improved Critical", description: "Attack rolls score a critical hit on a 19 or 20." },
    { level: 6, name: "Extra Attack", description: "Attack twice when taking the Attack action." },
    { level: 7, name: "Battle Readiness", description: "Advantage on initiative rolls." },
    { level: 10, name: "Improved Defense", description: "Armor Class increases by 1." },
    { level: 11, name: "Indomitable", description: "Reroll a failed saving throw once per long rest." },
    { level: 15, name: "Extra Attack (2 extra)", description: "Attack three times when taking the Attack action." },
    { level: 18, name: "Indomitable (2 uses)", description: "Use Indomitable twice per long rest." },
    { level: 20, name: "Second Wind (2 uses)", description: "Use Second Wind twice between rests." },
  ],
  abilities: [
    {
      id: "secondWind",
      name: "Second Wind",
      level: 2,
      refresh: "shortRest",
      uses: 1,
      usesByLevel: [{ level: 20, uses: 2 }],
      resource: "bonusAction",
      description: "Heal 1d10 + sidekick level HP.",
    },
    {
      id: "indomitable",
      name: "Indomitable",
      level: 11,
      refresh: "longRest",
      uses: 1,
      usesByLevel: [{ level: 18, uses: 2 }],
      resource: "reaction",
      description: "Automatically reroll a failed saving throw.",
    },
  ],
  equipment: {},
  inventory: {
    money: { cp: 0, sp: 0, gp: 0 },
    items: [],
  },
});
})();
