(() => {
window.DungeonContent.register("classes", "sidekick-expert", {
  hidden: true,
  sidekickOnly: true,
  name: "Expert Sidekick",
  className: "Expert Sidekick",
  classId: "sidekick-expert",
  classRole: "expert",
  casterType: "none",
  role: "Level 1 Expert Sidekick",
  level: 1,
  xp: 0,
  hitDie: 8,
  maxHp: 8,
  abilityMods: { dex: 2, int: 1, cha: 1 },
  baseAc: 10,
  attackBonus: 4,
  damage: { count: 1, sides: 6, bonus: 2, type: "piercing", label: "1d6 + 2 piercing" },
  initiativeBonus: 2,
  speedFeet: 30,
  armorProficiencies: ["light"],
  weaponProficiencies: [],
  savingThrowProficiencies: ["dex"],
  skillProficiencies: [],
  token: "E",
  classFeatures: [
    { level: 1, name: "Bonus Proficiencies", description: "The sidekick gains save, skill, armor, and sometimes tool and weapon training." },
    { level: 1, name: "Helpful", description: "The sidekick can take the Help action as a bonus action." },
    { level: 2, name: "Cunning Action", description: "Dash, Disengage, or Hide as a bonus action." },
    { level: 3, name: "Expertise", description: "Double proficiency for two chosen skills." },
    { level: 6, name: "Coordinated Strike", description: "Helpful can aid attacks up to 30 feet away and primes extra damage." },
    { level: 7, name: "Evasion", description: "Avoid or reduce damage on Dexterity saves." },
    { level: 11, name: "Inspiring Help", description: "Help grants an extra 1d6 bonus." },
    { level: 14, name: "Reliable Talent", description: "Proficient ability checks treat d20 rolls below 10 as 10." },
    { level: 15, name: "Expertise", description: "Choose two more skill proficiencies for Expertise." },
    { level: 18, name: "Sharp Mind", description: "Gain another mental saving throw proficiency." },
    { level: 20, name: "Inspiring Help (2d6)", description: "Help grants a 2d6 bonus." },
  ],
  abilities: [
    {
      id: "sidekickHelpful",
      name: "Helpful",
      level: 1,
      refresh: "turn",
      uses: 1,
      resource: "bonusAction",
      description: "Use Help as a bonus action. At higher levels it can inspire and coordinate attacks.",
    },
    {
      id: "cunningActionDash",
      name: "Cunning Action: Dash",
      level: 2,
      refresh: "turn",
      uses: 1,
      resource: "bonusAction",
      description: "Dash as a bonus action.",
    },
    {
      id: "cunningActionDisengage",
      name: "Cunning Action: Disengage",
      level: 2,
      refresh: "turn",
      uses: 1,
      resource: "bonusAction",
      description: "Disengage as a bonus action.",
    },
    {
      id: "cunningActionHide",
      name: "Cunning Action: Hide",
      level: 2,
      refresh: "turn",
      uses: 1,
      resource: "bonusAction",
      description: "Hide as a bonus action. This grants advantage to the next attack this turn.",
    },
  ],
  equipment: {},
  inventory: {
    money: { cp: 0, sp: 0, gp: 0 },
    items: [],
  },
});
})();
