(() => {
const pactSpellPoints = { 1: 2, 2: 4, 3: 6, 4: 6, 5: 10, 6: 10, 7: 12, 8: 12, 9: 14, 10: 14, 11: 21, 12: 21, 13: 21, 14: 21, 15: 21, 16: 21, 17: 28, 18: 28, 19: 28, 20: 28 };

const invocationOptions = [
  { id: "agonizingBlast", name: "Agonizing Blast", level: 2, description: "Add Charisma to each Eldritch Blast beam's damage.", mode: "passive" },
  { id: "repellingBlast", name: "Repelling Blast", level: 2, description: "Eldritch Blast pushes a hit enemy 10 ft away when space allows.", mode: "passive" },
  { id: "eldritchSpear", name: "Eldritch Spear", level: 2, description: "Eldritch Blast reaches across extreme distance.", mode: "passive" },
  { id: "armorOfShadows", name: "Armor of Shadows", level: 2, description: "At will, wrap yourself in Mage Armor for +3 AC.", mode: "active", resource: "action" },
  { id: "fiendishVigor", name: "Fiendish Vigor", level: 2, description: "At will, gain a small shield of temporary hit points.", mode: "active", resource: "bonusAction" },
  { id: "devilsSight", name: "Devil's Sight", level: 2, description: "Your magic ignores magical darkness and deep shadow penalties.", mode: "passive" },
  { id: "eldritchMind", name: "Eldritch Mind", level: 2, description: "Add +5 to concentration saves.", mode: "passive" },
  { id: "hexingBlast", name: "Hexing Blast", level: 3, description: "Eldritch Blast hits bite harder against Hexed targets.", mode: "passive" },
  { id: "graspOfHadar", name: "Grasp of Hadar", level: 3, description: "Eldritch Blast can pull a hit enemy closer when space allows.", mode: "passive" },
  { id: "thirstingBlade", name: "Thirsting Blade", level: 5, description: "Attack twice when you take the Attack action with a pact weapon.", mode: "passive" },
  { id: "eldritchAegis", name: "Eldritch Aegis", level: 5, description: "Custom invocation: after spending pact magic, gain +2 AC for a round.", mode: "passive" },
  { id: "patronsStep", name: "Patron's Step", level: 5, description: "Custom invocation: after spending pact magic, gain 15 ft of movement.", mode: "passive" },
  { id: "oneWithShadows", name: "One with Shadows", level: 5, description: "At will, blur into shadow for defense and advantage on your next strike.", mode: "active", resource: "bonusAction" },
  { id: "mireTheMind", name: "Mire the Mind", level: 5, description: "At will, mire a visible enemy, slowing and weakening its next attack.", mode: "active", resource: "action" },
  { id: "voidLance", name: "Void Lance", level: 7, description: "Custom invocation: Eldritch Blast slows enemies it hits.", mode: "passive" },
  { id: "witchSight", name: "Witch Sight", level: 7, description: "Gain advantage against frightened, hexed, or darkness-wrapped enemies.", mode: "passive" },
  { id: "soulLeech", name: "Soul Leech", level: 7, description: "When your Eldritch Blast drops an enemy, gain temporary HP.", mode: "passive" },
  { id: "ascendantStep", name: "Ascendant Step", level: 9, description: "At will, float through battle with extra movement and defense.", mode: "active", resource: "bonusAction" },
  { id: "dreadfulWord", name: "Dreadful Word", level: 9, description: "At will, speak a patron's word to frighten nearby visible enemies.", mode: "active", resource: "action" },
  { id: "lifedrinker", name: "Lifedrinker", level: 12, description: "Your weapon hits drink life, adding necrotic damage and a little healing.", mode: "passive" },
  { id: "eldritchDoom", name: "Eldritch Doom", level: 15, description: "Eldritch Blast critical hits also stun the target briefly.", mode: "passive" },
  { id: "patronsAegis", name: "Patron's Aegis", level: 15, description: "Custom invocation: after spending pact magic, gain broad damage resistance for a round.", mode: "passive" },
];

const pactBoonOptions = [
  { id: "pactBlade", name: "Pact of the Blade", level: 3, description: "Bind your weapon to your pact. Gain a pact blade surge and stronger melee pressure." },
  { id: "pactChain", name: "Pact of the Chain", level: 3, description: "Call an occult familiar that fights beside the party for the encounter." },
  { id: "pactTome", name: "Pact of the Tome", level: 3, description: "Receive a Book of Shadows, extra cantrips, and a spell-point recovery trick." },
  { id: "pactTalisman", name: "Pact of the Talisman", level: 3, description: "Carry a protective charm that can ward you or an ally." },
  { id: "pactStar", name: "Pact of the Star", level: 3, description: "Custom pact: chart an omen that burns and disorients a chosen enemy." },
  { id: "pactShadow", name: "Pact of the Shadow", level: 3, description: "Custom pact: step into your patron's shadow for defense, movement, and advantage." },
];

window.DungeonContent.register("classes", "warlock", {
  name: "Pactbound",
  className: "Warlock",
  classId: "warlock",
  classRole: "warlock",
  casterType: "pact",
  role: "Level 1 Warlock",
  level: 1,
  xp: 0,
  hitDie: 8,
  maxHp: 10,
  abilityMods: { str: 0, dex: 1, con: 2, wis: 1, cha: 2 },
  baseAc: 10,
  attackBonus: 4,
  damage: { count: 1, sides: 8, bonus: 1, type: "piercing", label: "1d8 + 1 piercing" },
  initiativeBonus: 1,
  speedFeet: 30,
  armorProficiencies: ["light"],
  weaponProficiencies: ["simple"],
  spellcastingAbility: "cha",
  spellPointProgression: pactSpellPoints,
  spellList: ["armor_of_agathys", "arms_of_hadar", "hex", "hellish_rebuke", "cause_fear", "darkness", "hold_person", "misty_step", "hunger_of_hadar", "vampiric_touch", "fly"],
  cantripList: ["mage-hand", "blade-ward", "mind-sliver", "eldritch-blast", "thunderclap", "chill-touch", "booming-blade", "frostbite", "green-flame-blade", "poison-spray", "toll-the-dead"],
  spells: [],
  token: "Wk",
  classFeatures: [
    { level: 1, name: "Pact Magic", description: "Cast warlock spells through pact-granted power that refreshes quickly." },
    { level: 1, name: "Eldritch Blast", description: "Hurl a signature beam of force at your enemies." },
    { level: 2, name: "Eldritch Invocations", description: "Choose occult gifts that reshape your warlock talents." },
    { level: 3, name: "Pact Boon", description: "Choose Pact of the Blade, Chain, Tome, Talisman, Star, or Shadow." },
    { level: 5, name: "Eldritch Invocation", description: "Choose one additional invocation." },
    { level: 7, name: "Eldritch Invocation", description: "Choose one additional invocation." },
    { level: 9, name: "Eldritch Invocation", description: "Choose one additional invocation." },
    { level: 11, name: "Mystic Arcanum", description: "Once per long rest, invoke patron magic as a high-power force burst that can briefly banish a foe." },
    { level: 12, name: "Eldritch Invocation", description: "Choose one additional invocation." },
    { level: 15, name: "Eldritch Invocation", description: "Choose one additional invocation." },
    { level: 18, name: "Eldritch Invocation", description: "Choose one additional invocation." },
    { level: 20, name: "Eldritch Master", description: "Restore pact magic through a brief appeal to your patron." },
  ],
  invocationOptions,
  pactBoonOptions,
  abilities: [
    ...invocationOptions.map((option) => ({
      id: option.id,
      name: option.name,
      level: option.level,
      invocationOption: true,
      resource: option.mode === "active" ? option.resource ?? "action" : "passive",
      refresh: option.mode === "active" ? "turn" : "longRest",
      uses: option.mode === "active" ? 99 : 0,
      description: option.description,
    })),
    { id: "pactBladeSurge", name: "Pact Blade Surge", level: 3, pactBoon: "pactBlade", refresh: "turn", uses: 1, resource: "bonusAction", description: "Charge your pact weapon. Your next melee hit deals extra force damage.", subclassEffect: { kind: "selfStatus", status: { id: "pact-blade-surge", label: "Pact Blade", weaponRider: true, damageBonus: 6, damageType: "force", expiresAtEndOfTurn: true } } },
    { id: "pactFamiliar", name: "Pact Familiar", level: 3, pactBoon: "pactChain", refresh: "shortRest", uses: 1, resource: "action", description: "Summon a pact familiar that harasses enemies from range.", subclassEffect: { kind: "summonAlly", profile: "rangedKiter", name: "Pact Familiar", durationRounds: 99 } },
    { id: "bookOfShadows", name: "Book of Shadows", level: 3, pactBoon: "pactTome", refresh: "shortRest", uses: 1, resource: "bonusAction", description: "Open the book and recover a little pact magic.", subclassEffect: { kind: "restoreSpellPoints", amount: 2 } },
    { id: "talismanWard", name: "Talisman Ward", level: 3, pactBoon: "pactTalisman", refresh: "shortRest", uses: 2, resource: "bonusAction", description: "Bless yourself or an ally with AC and save protection.", subclassEffect: { kind: "allyStatus", target: "selfOrAlly", status: { id: "talisman-ward", label: "Talisman Ward", acBonus: 1, saveBonus: 2, durationRounds: 3 } } },
    { id: "starOmen", name: "Star Omen", level: 3, pactBoon: "pactStar", refresh: "shortRest", uses: 1, resource: "action", description: "Mark a visible enemy with starlight, dealing radiant damage and leaving it shaken.", subclassEffect: { kind: "damageTarget", dice: { count: 2, sides: 8 }, damageType: "radiant", riderStatus: "shaken" } },
    { id: "shadowVeil", name: "Shadow Veil", level: 3, pactBoon: "pactShadow", refresh: "shortRest", uses: 1, resource: "bonusAction", description: "Slip into patron-shadow, gaining movement, defense, and advantage.", subclassEffect: { kind: "selfStatus", status: { id: "shadow-veil", label: "Shadow Veil", acBonus: 2, attackAdvantage: true, speedBonusFeet: 15, durationRounds: 2 } } },
    { id: "mysticArcanum", name: "Mystic Arcanum", level: 11, refresh: "longRest", uses: 1, resource: "action", description: "Call on a once-per-rest arcanum. A visible enemy takes 6d8 force damage and is briefly banished.", subclassEffect: { kind: "damageTarget", dice: { count: 6, sides: 8 }, damageType: "force", riderStatus: "banished" } },
    { id: "eldritchMaster", name: "Eldritch Master", level: 20, refresh: "longRest", uses: 1, resource: "action", description: "Restore pact spell points." },
  ],
  equipment: { mainHand: "crossbow-light", torso: "leather", quiver: "bolts-20" },
  inventory: { money: { cp: 0, sp: 0, gp: 0 }, items: ["crossbow-light", "bolts-20", "leather", "dagger", "dagger"] },
  startingGear: {
    equipment: { torso: "leather" },
    inventory: ["leather"],
    steps: [
      {
        title: "Starting Weapon",
        message: "Choose your warlock weapon.",
        choices: [
          { value: "light-crossbow", label: "Light Crossbow and 20 Bolts", equipment: { mainHand: "crossbow-light" }, inventory: ["crossbow-light", "bolts-20"], quiver: "bolts-20" },
          {
            value: "simple",
            label: "Any simple weapon",
            select: { pool: "simpleWeapons", title: "Choose Simple Weapon", message: "Select a simple weapon.", label: "Weapon", slot: "mainHand" },
          },
        ],
      },
      {
        title: "Second Weapon",
        message: "Choose one additional simple weapon.",
        choices: [
          {
            value: "simple",
            label: "Any simple weapon",
            select: { pool: "simpleWeapons", title: "Choose Simple Weapon", message: "Select a simple weapon.", label: "Weapon", slot: "" },
          },
        ],
      },
      {
        title: "Daggers",
        message: "Your warlock also starts with two daggers.",
        choices: [
          { value: "daggers", label: "Two Daggers", inventory: ["dagger", "dagger"] },
        ],
      },
    ],
  },
});
})();
