(() => {
  const entries = [
    { name: "Aelar", gender: "m" },
    { name: "Aelira", gender: "f" },
    { name: "Aerendyl", gender: "d" },
    { name: "Althaea", gender: "f" },
    { name: "Ansel", gender: "m" },
    { name: "Arannis", gender: "m" },
    { name: "Aric", gender: "m" },
    { name: "Asha", gender: "f" },
    { name: "Baern", gender: "m" },
    { name: "Berris", gender: "d" },
    { name: "Borin", gender: "m" },
    { name: "Bram", gender: "m" },
    { name: "Brynn", gender: "d" },
    { name: "Cael", gender: "m" },
    { name: "Calder", gender: "m" },
    { name: "Calla", gender: "f" },
    { name: "Cedric", gender: "m" },
    { name: "Cora", gender: "f" },
    { name: "Daelin", gender: "m" },
    { name: "Dain", gender: "m" },
    { name: "Dara", gender: "f" },
    { name: "Darian", gender: "m" },
    { name: "Delia", gender: "f" },
    { name: "Dorn", gender: "m" },
    { name: "Edrin", gender: "m" },
    { name: "Eira", gender: "f" },
    { name: "Eldon", gender: "m" },
    { name: "Elowen", gender: "f" },
    { name: "Ember", gender: "d" },
    { name: "Eryn", gender: "d" },
    { name: "Faelar", gender: "m" },
    { name: "Fenna", gender: "f" },
    { name: "Finn", gender: "m" },
    { name: "Garrick", gender: "m" },
    { name: "Gilda", gender: "f" },
    { name: "Glim", gender: "d" },
    { name: "Grenda", gender: "f" },
    { name: "Grond", gender: "m" },
    { name: "Hadrian", gender: "m" },
    { name: "Halia", gender: "f" },
    { name: "Harbek", gender: "m" },
    { name: "Helja", gender: "f" },
    { name: "Ilyra", gender: "f" },
    { name: "Ivor", gender: "m" },
    { name: "Jarek", gender: "m" },
    { name: "Jora", gender: "f" },
    { name: "Kael", gender: "m" },
    { name: "Kara", gender: "f" },
    { name: "Keth", gender: "m" },
    { name: "Kiera", gender: "f" },
    { name: "Korvin", gender: "m" },
    { name: "Laucian", gender: "m" },
    { name: "Leena", gender: "f" },
    { name: "Liora", gender: "f" },
    { name: "Lirael", gender: "f" },
    { name: "Luken", gender: "m" },
    { name: "Maelis", gender: "f" },
    { name: "Mara", gender: "f" },
    { name: "Merric", gender: "m" },
    { name: "Mira", gender: "f" },
    { name: "Morgran", gender: "m" },
    { name: "Nalia", gender: "f" },
    { name: "Neris", gender: "d" },
    { name: "Nim", gender: "d" },
    { name: "Nora", gender: "f" },
    { name: "Oren", gender: "m" },
    { name: "Orla", gender: "f" },
    { name: "Osric", gender: "m" },
    { name: "Perrin", gender: "d" },
    { name: "Petra", gender: "f" },
    { name: "Quarion", gender: "m" },
    { name: "Quinn", gender: "d" },
    { name: "Ragna", gender: "f" },
    { name: "Rurik", gender: "m" },
    { name: "Saela", gender: "f" },
    { name: "Seraphine", gender: "f" },
    { name: "Sigrid", gender: "f" },
    { name: "Silas", gender: "m" },
    { name: "Sora", gender: "d" },
    { name: "Soveliss", gender: "m" },
    { name: "Talia", gender: "f" },
    { name: "Tamsin", gender: "d" },
    { name: "Tarin", gender: "d" },
    { name: "Thalia", gender: "f" },
    { name: "Thamior", gender: "m" },
    { name: "Thora", gender: "f" },
    { name: "Torinn", gender: "m" },
    { name: "Ulric", gender: "m" },
    { name: "Una", gender: "f" },
    { name: "Valanthe", gender: "f" },
    { name: "Varek", gender: "m" },
    { name: "Vasha", gender: "d" },
    { name: "Veyra", gender: "f" },
    { name: "Wenna", gender: "f" },
    { name: "Wulfric", gender: "m" },
    { name: "Xanaphia", gender: "f" },
    { name: "Yara", gender: "f" },
    { name: "Yorven", gender: "m" },
    { name: "Zanna", gender: "f" },
    { name: "Zorric", gender: "m" },
  ];
  const names = entries.map((entry) => entry.name);

  window.DepthboundHeroNames = {
    entries,
    names,
    randomEntry(random = Math.random) {
      return entries[Math.floor(random() * entries.length)] ?? { name: "New Hero", gender: "d" };
    },
    random() {
      return names[Math.floor(Math.random() * names.length)] ?? "New Hero";
    },
  };
})();
