(() => {
const sharedSummonTags = ["summon", "companion"];

function summon(id, definition) {
  const tokenSlug = String(definition.name ?? id).toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
  window.DungeonContent.register("monsters", id, {
    category: definition.category ?? 1,
    xp: 0,
    behavior: definition.behavior ?? "melee",
    specialAbility: definition.specialAbility ?? [],
    initiativeBonus: definition.initiativeBonus ?? definition.abilityMods?.dex ?? 0,
    tokenArt: `assets/tokens/${tokenSlug}.jpg`,
    ...definition,
    tokenArt: definition.tokenArt ?? `assets/tokens/${tokenSlug}.jpg`,
    tags: [...sharedSummonTags, ...(definition.tags ?? [])],
  });
}

function damage(count, sides, bonus, type, label, range = { kind: "melee", feet: 5 }) {
  return { count, sides, bonus, type, attackType: "weapon", label, range };
}

summon("summonFamiliarBat", {
  name: "Familiar Bat",
  role: "Tiny flying scout",
  tags: ["familiar", "beast", "bat", "flying", "blindsight"],
  maxHp: 1,
  ac: 12,
  baseAc: 12,
  attackBonus: 2,
  damage: damage(1, 1, 0, "bludgeoning", "1 bludgeoning"),
  abilityScores: { str: 2, dex: 15, con: 8, int: 2, wis: 12, cha: 4 },
  abilityMods: { str: -4, dex: 2, con: -1, int: -4, wis: 1, cha: -3 },
  baseAttackAbilityMod: 2,
  senses: { blindsight: 60 },
  speedFeet: 5,
  flying: true,
  token: "B",
});

summon("summonFamiliarCat", {
  name: "Familiar Cat",
  role: "Tiny stealthy scout",
  tags: ["familiar", "beast", "cat", "darkvision"],
  maxHp: 2,
  ac: 12,
  baseAc: 12,
  attackBonus: 2,
  damage: damage(1, 1, 0, "slashing", "1 slashing"),
  abilityScores: { str: 3, dex: 15, con: 10, int: 3, wis: 12, cha: 7 },
  abilityMods: { str: -4, dex: 2, con: 0, int: -4, wis: 1, cha: -2 },
  baseAttackAbilityMod: 2,
  skillProficiencies: ["perception", "stealth"],
  senses: { darkvision: 60 },
  speedFeet: 40,
  token: "C",
});

summon("summonFamiliarCrab", {
  name: "Familiar Crab",
  role: "Tiny amphibious scout",
  tags: ["familiar", "beast", "crab", "swim"],
  maxHp: 2,
  ac: 11,
  baseAc: 11,
  attackBonus: 0,
  damage: damage(1, 1, 0, "bludgeoning", "1 bludgeoning"),
  abilityScores: { str: 2, dex: 11, con: 10, int: 1, wis: 8, cha: 2 },
  abilityMods: { str: -4, dex: 0, con: 0, int: -5, wis: -1, cha: -4 },
  baseAttackAbilityMod: 0,
  senses: { blindsight: 30 },
  speedFeet: 20,
  swimSpeedFeet: 20,
  token: "C",
});

summon("summonFamiliarFrog", {
  name: "Familiar Frog",
  role: "Tiny amphibious scout",
  tags: ["familiar", "beast", "frog", "toad", "swim"],
  maxHp: 1,
  ac: 11,
  baseAc: 11,
  attackBonus: 1,
  damage: damage(1, 1, 0, "bludgeoning", "1 bludgeoning"),
  abilityScores: { str: 1, dex: 13, con: 8, int: 1, wis: 8, cha: 3 },
  abilityMods: { str: -5, dex: 1, con: -1, int: -5, wis: -1, cha: -4 },
  baseAttackAbilityMod: 1,
  senses: { darkvision: 30 },
  speedFeet: 20,
  swimSpeedFeet: 20,
  token: "F",
});

summon("summonFamiliarHawk", {
  name: "Familiar Hawk",
  role: "Tiny aerial scout",
  tags: ["familiar", "beast", "hawk", "flying"],
  maxHp: 1,
  ac: 13,
  baseAc: 13,
  attackBonus: 5,
  damage: damage(1, 1, 0, "slashing", "1 slashing"),
  abilityScores: { str: 5, dex: 16, con: 8, int: 2, wis: 14, cha: 6 },
  abilityMods: { str: -3, dex: 3, con: -1, int: -4, wis: 2, cha: -2 },
  baseAttackAbilityMod: 3,
  skillProficiencies: ["perception"],
  speedFeet: 10,
  flying: true,
  token: "H",
});

summon("summonFamiliarLizard", {
  name: "Familiar Lizard",
  role: "Tiny wall-crawling scout",
  tags: ["familiar", "beast", "lizard", "climb"],
  maxHp: 2,
  ac: 10,
  baseAc: 10,
  attackBonus: 0,
  damage: damage(1, 1, 0, "piercing", "1 piercing"),
  abilityScores: { str: 2, dex: 11, con: 10, int: 1, wis: 8, cha: 3 },
  abilityMods: { str: -4, dex: 0, con: 0, int: -5, wis: -1, cha: -4 },
  baseAttackAbilityMod: 0,
  senses: { darkvision: 30 },
  speedFeet: 20,
  climbSpeedFeet: 20,
  token: "L",
});

summon("summonFamiliarOctopus", {
  name: "Familiar Octopus",
  role: "Tiny aquatic grappler",
  tags: ["familiar", "beast", "octopus", "swim"],
  maxHp: 3,
  ac: 12,
  baseAc: 12,
  attackBonus: 4,
  damage: damage(1, 1, 0, "bludgeoning", "1 bludgeoning"),
  abilityScores: { str: 4, dex: 15, con: 11, int: 3, wis: 10, cha: 4 },
  abilityMods: { str: -3, dex: 2, con: 0, int: -4, wis: 0, cha: -3 },
  baseAttackAbilityMod: 2,
  skillProficiencies: ["perception", "stealth"],
  senses: { darkvision: 30 },
  speedFeet: 5,
  swimSpeedFeet: 30,
  token: "O",
});

summon("summonFamiliarOwl", {
  name: "Familiar Owl",
  role: "Tiny night scout",
  tags: ["familiar", "beast", "owl", "flying", "darkvision"],
  maxHp: 1,
  ac: 11,
  baseAc: 11,
  attackBonus: 3,
  damage: damage(1, 1, 0, "slashing", "1 slashing"),
  abilityScores: { str: 3, dex: 13, con: 8, int: 2, wis: 12, cha: 7 },
  abilityMods: { str: -4, dex: 1, con: -1, int: -4, wis: 1, cha: -2 },
  baseAttackAbilityMod: 1,
  skillProficiencies: ["perception", "stealth"],
  senses: { darkvision: 120 },
  speedFeet: 5,
  flying: true,
  token: "O",
});

summon("summonFamiliarPoisonousSnake", {
  name: "Familiar Poisonous Snake",
  role: "Tiny venomous scout",
  tags: ["familiar", "beast", "snake", "poison", "swim"],
  maxHp: 2,
  ac: 13,
  baseAc: 13,
  attackBonus: 5,
  damage: damage(1, 1, 0, "piercing", "1 piercing"),
  abilityScores: { str: 2, dex: 16, con: 11, int: 1, wis: 10, cha: 3 },
  abilityMods: { str: -4, dex: 3, con: 0, int: -5, wis: 0, cha: -4 },
  baseAttackAbilityMod: 3,
  senses: { blindsight: 10 },
  speedFeet: 30,
  swimSpeedFeet: 30,
  token: "S",
});

summon("summonFamiliarFish", {
  name: "Familiar Fish",
  role: "Tiny aquatic scout",
  tags: ["familiar", "beast", "fish", "quipper", "swim"],
  maxHp: 1,
  ac: 13,
  baseAc: 13,
  attackBonus: 5,
  damage: damage(1, 1, 0, "piercing", "1 piercing"),
  abilityScores: { str: 2, dex: 16, con: 9, int: 1, wis: 7, cha: 2 },
  abilityMods: { str: -4, dex: 3, con: -1, int: -5, wis: -2, cha: -4 },
  baseAttackAbilityMod: 3,
  senses: { darkvision: 60 },
  speedFeet: 0,
  swimSpeedFeet: 40,
  token: "F",
});

summon("summonFamiliarRat", {
  name: "Familiar Rat",
  role: "Tiny infiltrator",
  tags: ["familiar", "beast", "rat", "darkvision"],
  maxHp: 1,
  ac: 10,
  baseAc: 10,
  attackBonus: 0,
  damage: damage(1, 1, 0, "piercing", "1 piercing"),
  abilityScores: { str: 2, dex: 11, con: 9, int: 2, wis: 10, cha: 4 },
  abilityMods: { str: -4, dex: 0, con: -1, int: -4, wis: 0, cha: -3 },
  baseAttackAbilityMod: 0,
  senses: { darkvision: 30 },
  speedFeet: 20,
  token: "R",
});

summon("summonFamiliarRaven", {
  name: "Familiar Raven",
  role: "Tiny mimic scout",
  tags: ["familiar", "beast", "raven", "flying"],
  maxHp: 1,
  ac: 12,
  baseAc: 12,
  attackBonus: 4,
  damage: damage(1, 1, 0, "piercing", "1 piercing"),
  abilityScores: { str: 2, dex: 14, con: 8, int: 2, wis: 12, cha: 6 },
  abilityMods: { str: -4, dex: 2, con: -1, int: -4, wis: 1, cha: -2 },
  baseAttackAbilityMod: 2,
  skillProficiencies: ["perception"],
  speedFeet: 10,
  flying: true,
  token: "R",
});

summon("summonFamiliarSeaHorse", {
  name: "Familiar Sea Horse",
  role: "Tiny aquatic scout",
  tags: ["familiar", "beast", "sea-horse", "swim"],
  maxHp: 1,
  ac: 11,
  baseAc: 11,
  attackBonus: 0,
  damage: damage(1, 1, 0, "bludgeoning", "1 bludgeoning"),
  abilityScores: { str: 1, dex: 12, con: 8, int: 1, wis: 10, cha: 2 },
  abilityMods: { str: -5, dex: 1, con: -1, int: -5, wis: 0, cha: -4 },
  baseAttackAbilityMod: 1,
  speedFeet: 0,
  swimSpeedFeet: 20,
  token: "S",
});

summon("summonFamiliarSpider", {
  name: "Familiar Spider",
  role: "Tiny wall-crawling scout",
  tags: ["familiar", "beast", "spider", "climb", "darkvision"],
  maxHp: 1,
  ac: 12,
  baseAc: 12,
  attackBonus: 4,
  damage: damage(1, 1, 0, "piercing", "1 piercing"),
  abilityScores: { str: 2, dex: 14, con: 8, int: 1, wis: 10, cha: 2 },
  abilityMods: { str: -4, dex: 2, con: -1, int: -5, wis: 0, cha: -4 },
  baseAttackAbilityMod: 2,
  skillProficiencies: ["stealth"],
  senses: { darkvision: 30 },
  speedFeet: 20,
  climbSpeedFeet: 20,
  token: "S",
});

summon("summonFamiliarWeasel", {
  name: "Familiar Weasel",
  role: "Tiny stealth scout",
  tags: ["familiar", "beast", "weasel"],
  maxHp: 1,
  ac: 13,
  baseAc: 13,
  attackBonus: 5,
  damage: damage(1, 1, 0, "piercing", "1 piercing"),
  abilityScores: { str: 3, dex: 16, con: 8, int: 2, wis: 12, cha: 3 },
  abilityMods: { str: -4, dex: 3, con: -1, int: -4, wis: 1, cha: -4 },
  baseAttackAbilityMod: 3,
  skillProficiencies: ["perception", "stealth"],
  speedFeet: 30,
  token: "W",
});

summon("summonPactFamiliarImp", {
  name: "Pact Familiar Imp",
  role: "Tiny infernal infiltrator",
  tags: ["pact-familiar", "familiar", "fiend", "imp", "flying", "darkvision"],
  maxHp: 10,
  ac: 13,
  baseAc: 13,
  attackBonus: 5,
  damage: damage(1, 4, 3, "piercing", "1d4 + 3 piercing"),
  abilityScores: { str: 6, dex: 17, con: 13, int: 11, wis: 12, cha: 14 },
  abilityMods: { str: -2, dex: 3, con: 1, int: 0, wis: 1, cha: 2 },
  baseAttackAbilityMod: 3,
  skillProficiencies: ["deception", "insight", "persuasion", "stealth"],
  damageResistances: ["cold", "bludgeoning", "piercing", "slashing"],
  damageImmunities: ["fire", "poison"],
  conditionImmunities: ["poisoned"],
  senses: { darkvision: 120 },
  speedFeet: 20,
  flying: true,
  token: "I",
});

summon("summonPactFamiliarPseudodragon", {
  name: "Pact Familiar Pseudodragon",
  role: "Tiny draconic scout",
  tags: ["pact-familiar", "familiar", "dragon", "pseudodragon", "flying", "darkvision"],
  maxHp: 7,
  ac: 13,
  baseAc: 13,
  attackBonus: 4,
  damage: damage(1, 4, 2, "piercing", "1d4 + 2 piercing"),
  abilityScores: { str: 6, dex: 15, con: 13, int: 10, wis: 12, cha: 10 },
  abilityMods: { str: -2, dex: 2, con: 1, int: 0, wis: 1, cha: 0 },
  baseAttackAbilityMod: 2,
  skillProficiencies: ["perception", "stealth"],
  senses: { blindsight: 10, darkvision: 60 },
  speedFeet: 15,
  flying: true,
  token: "D",
});

summon("summonPactFamiliarQuasit", {
  name: "Pact Familiar Quasit",
  role: "Tiny abyssal trickster",
  tags: ["pact-familiar", "familiar", "fiend", "quasit", "darkvision"],
  maxHp: 7,
  ac: 13,
  baseAc: 13,
  attackBonus: 4,
  damage: damage(1, 4, 3, "piercing", "1d4 + 3 piercing"),
  abilityScores: { str: 5, dex: 17, con: 10, int: 7, wis: 10, cha: 10 },
  abilityMods: { str: -3, dex: 3, con: 0, int: -2, wis: 0, cha: 0 },
  baseAttackAbilityMod: 3,
  skillProficiencies: ["stealth"],
  damageResistances: ["cold", "fire", "lightning", "bludgeoning", "piercing", "slashing"],
  damageImmunities: ["poison"],
  conditionImmunities: ["poisoned"],
  senses: { darkvision: 120 },
  speedFeet: 40,
  token: "Q",
});

summon("summonPactFamiliarSprite", {
  name: "Pact Familiar Sprite",
  role: "Tiny fey archer scout",
  tags: ["pact-familiar", "familiar", "fey", "sprite", "flying"],
  maxHp: 2,
  ac: 15,
  baseAc: 15,
  attackBonus: 6,
  damage: damage(1, 1, 0, "piercing", "1 piercing", { kind: "ranged", feet: 40 }),
  abilityScores: { str: 3, dex: 18, con: 10, int: 14, wis: 13, cha: 11 },
  abilityMods: { str: -4, dex: 4, con: 0, int: 2, wis: 1, cha: 0 },
  baseAttackAbilityMod: 4,
  skillProficiencies: ["perception", "stealth"],
  speedFeet: 10,
  flying: true,
  behavior: "rangedKiter",
  token: "S",
});

summon("summonRangerPanther", {
  name: "Ranger Panther",
  role: "Medium stealth ambusher",
  tags: ["ranger-companion", "beast", "cat", "panther", "darkvision"],
  maxHp: 13,
  ac: 12,
  baseAc: 12,
  attackBonus: 4,
  damage: damage(1, 6, 2, "slashing", "1d6 + 2 slashing"),
  abilityScores: { str: 14, dex: 15, con: 10, int: 3, wis: 14, cha: 7 },
  abilityMods: { str: 2, dex: 2, con: 0, int: -4, wis: 2, cha: -2 },
  baseAttackAbilityMod: 2,
  skillProficiencies: ["perception", "stealth"],
  senses: { darkvision: 60 },
  speedFeet: 50,
  climbSpeedFeet: 40,
  token: "P",
});

summon("summonRangerGiantBadger", {
  name: "Ranger Giant Badger",
  role: "Medium burrowing bruiser",
  tags: ["ranger-companion", "beast", "badger", "burrow", "darkvision"],
  maxHp: 13,
  ac: 10,
  baseAc: 10,
  attackBonus: 3,
  multiattack: { attacks: 2 },
  damage: damage(1, 6, 1, "slashing", "1d6 + 1 slashing"),
  abilityScores: { str: 13, dex: 10, con: 15, int: 2, wis: 12, cha: 5 },
  abilityMods: { str: 1, dex: 0, con: 2, int: -4, wis: 1, cha: -3 },
  baseAttackAbilityMod: 1,
  senses: { darkvision: 30 },
  speedFeet: 30,
  burrowSpeedFeet: 10,
  token: "B",
});

summon("summonRangerGiantCrab", {
  name: "Ranger Giant Crab",
  role: "Medium armored grappler",
  tags: ["ranger-companion", "beast", "crab", "swim", "blindsight"],
  maxHp: 13,
  ac: 15,
  baseAc: 15,
  attackBonus: 3,
  damage: damage(1, 6, 1, "bludgeoning", "1d6 + 1 bludgeoning"),
  abilityScores: { str: 13, dex: 15, con: 11, int: 1, wis: 9, cha: 3 },
  abilityMods: { str: 1, dex: 2, con: 0, int: -5, wis: -1, cha: -4 },
  baseAttackAbilityMod: 1,
  skillProficiencies: ["stealth"],
  senses: { blindsight: 30 },
  speedFeet: 30,
  swimSpeedFeet: 30,
  token: "C",
});

summon("summonRangerGiantFrog", {
  name: "Ranger Giant Frog",
  role: "Medium amphibious controller",
  tags: ["ranger-companion", "beast", "frog", "toad", "swim", "darkvision"],
  maxHp: 18,
  ac: 11,
  baseAc: 11,
  attackBonus: 3,
  damage: damage(1, 6, 1, "bludgeoning", "1d6 + 1 bludgeoning"),
  abilityScores: { str: 12, dex: 13, con: 11, int: 2, wis: 10, cha: 3 },
  abilityMods: { str: 1, dex: 1, con: 0, int: -4, wis: 0, cha: -4 },
  baseAttackAbilityMod: 1,
  senses: { darkvision: 30 },
  speedFeet: 30,
  swimSpeedFeet: 30,
  token: "F",
});

summon("summonRangerGiantPoisonousSnake", {
  name: "Ranger Giant Poisonous Snake",
  role: "Medium venom striker",
  tags: ["ranger-companion", "beast", "snake", "poison", "swim", "blindsight"],
  maxHp: 11,
  ac: 14,
  baseAc: 14,
  attackBonus: 6,
  damage: damage(1, 4, 4, "piercing", "1d4 + 4 piercing"),
  abilityScores: { str: 10, dex: 18, con: 13, int: 2, wis: 10, cha: 3 },
  abilityMods: { str: 0, dex: 4, con: 1, int: -4, wis: 0, cha: -4 },
  baseAttackAbilityMod: 4,
  senses: { blindsight: 10 },
  speedFeet: 30,
  swimSpeedFeet: 30,
  token: "S",
});

summon("summonRangerGiantWolfSpider", {
  name: "Ranger Giant Wolf Spider",
  role: "Medium climbing venom ambusher",
  tags: ["ranger-companion", "beast", "spider", "poison", "climb", "darkvision"],
  maxHp: 11,
  ac: 13,
  baseAc: 13,
  attackBonus: 3,
  damage: damage(1, 6, 1, "piercing", "1d6 + 1 piercing"),
  abilityScores: { str: 12, dex: 16, con: 13, int: 3, wis: 12, cha: 4 },
  abilityMods: { str: 1, dex: 3, con: 1, int: -4, wis: 1, cha: -3 },
  baseAttackAbilityMod: 3,
  skillProficiencies: ["perception", "stealth"],
  senses: { blindsight: 10, darkvision: 60 },
  speedFeet: 40,
  climbSpeedFeet: 40,
  token: "S",
});

summon("summonRangerPteranodon", {
  name: "Ranger Pteranodon",
  role: "Medium flying skirmisher",
  tags: ["ranger-companion", "beast", "pteranodon", "flying"],
  maxHp: 13,
  ac: 13,
  baseAc: 13,
  attackBonus: 3,
  damage: damage(2, 4, 1, "piercing", "2d4 + 1 piercing"),
  abilityScores: { str: 12, dex: 15, con: 10, int: 2, wis: 9, cha: 5 },
  abilityMods: { str: 1, dex: 2, con: 0, int: -4, wis: -1, cha: -3 },
  baseAttackAbilityMod: 2,
  skillProficiencies: ["perception"],
  speedFeet: 10,
  flying: true,
  token: "P",
});

summon("summonRangerMule", {
  name: "Ranger Mule",
  role: "Medium sturdy pack companion",
  tags: ["ranger-companion", "beast", "mule"],
  maxHp: 11,
  ac: 10,
  baseAc: 10,
  attackBonus: 2,
  damage: damage(1, 4, 2, "bludgeoning", "1d4 + 2 bludgeoning"),
  abilityScores: { str: 14, dex: 10, con: 13, int: 2, wis: 10, cha: 5 },
  abilityMods: { str: 2, dex: 0, con: 1, int: -4, wis: 0, cha: -3 },
  baseAttackAbilityMod: 2,
  speedFeet: 40,
  token: "M",
});

summon("summonRangerOwl", {
  name: "Ranger Owl",
  role: "Tiny night scout",
  tags: ["ranger-companion", "beast", "owl", "flying", "darkvision"],
  maxHp: 5,
  ac: 11,
  baseAc: 11,
  attackBonus: 3,
  damage: damage(1, 4, 1, "slashing", "1d4 + 1 slashing"),
  abilityScores: { str: 3, dex: 13, con: 8, int: 2, wis: 12, cha: 7 },
  abilityMods: { str: -4, dex: 1, con: -1, int: -4, wis: 1, cha: -2 },
  baseAttackAbilityMod: 1,
  skillProficiencies: ["perception", "stealth"],
  senses: { darkvision: 120 },
  speedFeet: 5,
  flying: true,
  token: "O",
});

summon("summonSteedWarhorse", {
  name: "Summoned Warhorse",
  role: "Large celestial mount",
  tags: ["steed", "beast", "horse", "mount"],
  maxHp: 19,
  ac: 11,
  baseAc: 11,
  attackBonus: 6,
  damage: damage(2, 6, 4, "bludgeoning", "2d6 + 4 bludgeoning"),
  abilityScores: { str: 18, dex: 12, con: 13, int: 6, wis: 12, cha: 7 },
  abilityMods: { str: 4, dex: 1, con: 1, int: -2, wis: 1, cha: -2 },
  baseAttackAbilityMod: 4,
  speedFeet: 60,
  token: "W",
});

summon("summonSteedPony", {
  name: "Summoned Pony",
  role: "Medium celestial mount",
  tags: ["steed", "beast", "pony", "mount"],
  maxHp: 11,
  ac: 10,
  baseAc: 10,
  attackBonus: 4,
  damage: damage(2, 4, 2, "bludgeoning", "2d4 + 2 bludgeoning"),
  abilityScores: { str: 15, dex: 10, con: 13, int: 6, wis: 11, cha: 7 },
  abilityMods: { str: 2, dex: 0, con: 1, int: -2, wis: 0, cha: -2 },
  baseAttackAbilityMod: 2,
  speedFeet: 40,
  token: "P",
});

summon("summonSteedCamel", {
  name: "Summoned Camel",
  role: "Large desert mount",
  tags: ["steed", "beast", "camel", "mount"],
  maxHp: 15,
  ac: 9,
  baseAc: 9,
  attackBonus: 5,
  damage: damage(1, 4, 3, "bludgeoning", "1d4 + 3 bludgeoning"),
  abilityScores: { str: 16, dex: 8, con: 14, int: 6, wis: 8, cha: 5 },
  abilityMods: { str: 3, dex: -1, con: 2, int: -2, wis: -1, cha: -3 },
  baseAttackAbilityMod: 3,
  speedFeet: 50,
  token: "C",
});

summon("summonSteedElk", {
  name: "Summoned Elk",
  role: "Large swift mount",
  tags: ["steed", "beast", "elk", "mount"],
  maxHp: 13,
  ac: 10,
  baseAc: 10,
  attackBonus: 5,
  damage: damage(1, 6, 3, "bludgeoning", "1d6 + 3 bludgeoning"),
  abilityScores: { str: 16, dex: 10, con: 12, int: 6, wis: 10, cha: 6 },
  abilityMods: { str: 3, dex: 0, con: 1, int: -2, wis: 0, cha: -2 },
  baseAttackAbilityMod: 3,
  speedFeet: 50,
  token: "E",
});

summon("summonSteedMastiff", {
  name: "Summoned Mastiff",
  role: "Medium loyal mount",
  tags: ["steed", "beast", "mastiff", "dog", "mount"],
  maxHp: 5,
  ac: 12,
  baseAc: 12,
  attackBonus: 3,
  damage: damage(1, 6, 1, "piercing", "1d6 + 1 piercing"),
  abilityScores: { str: 13, dex: 14, con: 12, int: 6, wis: 12, cha: 7 },
  abilityMods: { str: 1, dex: 2, con: 1, int: -2, wis: 1, cha: -2 },
  baseAttackAbilityMod: 1,
  skillProficiencies: ["perception"],
  speedFeet: 40,
  token: "M",
});

summon("summonGreaterSteedGriffon", {
  name: "Summoned Griffon",
  role: "Large flying divine mount",
  tags: ["greater-steed", "monstrosity", "griffon", "flying", "mount"],
  maxHp: 59,
  ac: 12,
  baseAc: 12,
  attackBonus: 6,
  damage: damage(2, 8, 4, "slashing", "2d8 + 4 slashing"),
  abilityScores: { str: 18, dex: 15, con: 16, int: 6, wis: 13, cha: 8 },
  abilityMods: { str: 4, dex: 2, con: 3, int: -2, wis: 1, cha: -1 },
  baseAttackAbilityMod: 4,
  skillProficiencies: ["perception"],
  speedFeet: 30,
  flying: true,
  token: "G",
});

summon("summonGreaterSteedPegasus", {
  name: "Summoned Pegasus",
  role: "Large flying celestial mount",
  tags: ["greater-steed", "celestial", "pegasus", "flying", "mount"],
  maxHp: 59,
  ac: 12,
  baseAc: 12,
  attackBonus: 6,
  damage: damage(2, 6, 4, "bludgeoning", "2d6 + 4 bludgeoning"),
  abilityScores: { str: 18, dex: 15, con: 16, int: 10, wis: 15, cha: 13 },
  abilityMods: { str: 4, dex: 2, con: 3, int: 0, wis: 2, cha: 1 },
  baseAttackAbilityMod: 4,
  skillProficiencies: ["perception"],
  speedFeet: 60,
  flying: true,
  token: "P",
});

summon("summonGreaterSteedPeryton", {
  name: "Summoned Peryton",
  role: "Medium flying predatory mount",
  tags: ["greater-steed", "monstrosity", "peryton", "flying", "mount"],
  maxHp: 33,
  ac: 13,
  baseAc: 13,
  attackBonus: 5,
  damage: damage(1, 8, 3, "piercing", "1d8 + 3 piercing"),
  abilityScores: { str: 16, dex: 12, con: 13, int: 6, wis: 12, cha: 10 },
  abilityMods: { str: 3, dex: 1, con: 1, int: -2, wis: 1, cha: 0 },
  baseAttackAbilityMod: 3,
  skillProficiencies: ["perception"],
  speedFeet: 20,
  flying: true,
  token: "P",
});

summon("summonGreaterSteedDireWolf", {
  name: "Summoned Dire Wolf",
  role: "Large fierce mount",
  tags: ["greater-steed", "beast", "wolf", "mount"],
  maxHp: 37,
  ac: 14,
  baseAc: 14,
  attackBonus: 5,
  damage: damage(2, 6, 3, "piercing", "2d6 + 3 piercing"),
  abilityScores: { str: 17, dex: 15, con: 15, int: 6, wis: 12, cha: 7 },
  abilityMods: { str: 3, dex: 2, con: 2, int: -2, wis: 1, cha: -2 },
  baseAttackAbilityMod: 3,
  skillProficiencies: ["perception", "stealth"],
  senses: { darkvision: 60 },
  speedFeet: 50,
  token: "D",
});

summon("summonGreaterSteedRhinoceros", {
  name: "Summoned Rhinoceros",
  role: "Large charging mount",
  tags: ["greater-steed", "beast", "rhinoceros", "mount"],
  maxHp: 45,
  ac: 11,
  baseAc: 11,
  attackBonus: 7,
  damage: damage(2, 8, 5, "bludgeoning", "2d8 + 5 bludgeoning"),
  abilityScores: { str: 21, dex: 8, con: 15, int: 6, wis: 12, cha: 6 },
  abilityMods: { str: 5, dex: -1, con: 2, int: -2, wis: 1, cha: -2 },
  baseAttackAbilityMod: 5,
  speedFeet: 40,
  token: "R",
});

summon("summonGreaterSteedSaberToothedTiger", {
  name: "Summoned Saber-Toothed Tiger",
  role: "Large stalking mount",
  tags: ["greater-steed", "beast", "cat", "tiger", "darkvision", "mount"],
  maxHp: 52,
  ac: 12,
  baseAc: 12,
  attackBonus: 6,
  damage: damage(2, 6, 5, "piercing", "2d6 + 5 piercing"),
  abilityScores: { str: 18, dex: 14, con: 15, int: 6, wis: 12, cha: 8 },
  abilityMods: { str: 4, dex: 2, con: 2, int: -2, wis: 1, cha: -1 },
  baseAttackAbilityMod: 4,
  skillProficiencies: ["perception", "stealth"],
  senses: { darkvision: 60 },
  speedFeet: 40,
  token: "T",
});
})();
