window.DungeonConfig = {
  gridSize: 7,
  feetPerSquare: 5,
  tileSizePx: 54,
  tokenSlideMs: 320,
  templates: {
    hero: {
      id: "hero",
      name: "Mira Vale",
      role: "Level 1 Fighter",
      maxHp: 14,
      ac: 16,
      attackBonus: 5,
      damage: { count: 1, sides: 8, bonus: 3, label: "1d8 + 3" },
      initiativeBonus: 2,
      speedFeet: 30,
      position: { x: 2, y: 4 },
      token: "M",
    },
    monster: {
      id: "monster",
      name: "Crypt Guard",
      role: "Armored skeleton",
      maxHp: 13,
      ac: 13,
      attackBonus: 4,
      damage: { count: 1, sides: 6, bonus: 2, label: "1d6 + 2" },
      initiativeBonus: 2,
      speedFeet: 30,
      behavior: "melee",
      position: { x: 4, y: 2 },
      token: "C",
    },
  },
};
