window.DungeonConfig = {
  gridSize: 72,
  feetPerSquare: 5,
  tileSizePx: 32,
  tokenSlideMs: 140,
  dungeon: {
    roomCount: 20,
    gridSize: 72,
  },
  defaultContent: {
    heroClass: "fighter",
    monster: "cryptGuard",
    dungeon: "generatedOldGuardroom",
    theme: "oldGuardroom",
    lootTable: "basicDungeon",
  },
  bugReport: {
    formUrl: "https://forms.gle/rLzd1mUpRm7abSB29",
    responseSheetUrl: "https://docs.google.com/spreadsheets/d/1vwoaKmapIZxBCVdIrFga6rN6hj2vTj9AAO0cHqxAU28/edit",
  },
  templates: {
    hero: {
      id: "hero",
      name: "Mira Vale",
      role: "Level 1 Fighter",
      level: 1,
      xp: 0,
      hitDie: 10,
      maxHp: 14,
      abilityMods: { str: 3, dex: 2 },
      baseAc: 10,
      attackBonus: 5,
      damage: { count: 1, sides: 4, bonus: 3, type: "bludgeoning", label: "1d4 + 3 bludgeoning" },
      initiativeBonus: 2,
      speedFeet: 30,
      position: { x: 0, y: 0 },
      token: "M",
      equipment: {
        mainHand: "longsword",
        offHand: null,
        head: null,
        torso: "chain-mail",
        boots: null,
        cloak: null,
        bracers: null,
        gauntlets: null,
        ring1: null,
        ring2: null,
        amulet: null,
      },
      inventory: {
        money: { cp: 0, sp: 0, gp: 0 },
        items: [
          "longsword",
          "chain-mail",
        ],
      },
    },
    monster: {
      id: "monster",
      name: "Crypt Guard",
      role: "Armored skeleton",
      maxHp: 13,
      xp: 50,
      ac: 13,
      attackBonus: 4,
      damage: { count: 1, sides: 6, bonus: 2, type: "piercing", label: "1d6 + 2 piercing" },
      initiativeBonus: 2,
      speedFeet: 30,
      behavior: "melee",
      position: { x: 0, y: 0 },
      token: "C",
    },
  },
};
