(() => {
window.DungeonContent.register("themes", "jungle", {
  name: "Jungle",
  description: "Dense canopy ruins, carnivorous plants, wet stone, tangled vines, humid pools, poisonous blooms, and hidden wild paths.",
  music: {
    exploration: "assets/sounds/music/forestOfTheBeasts-exploration.mp3",
    combat: "assets/sounds/music/forestOfTheBeasts-combat.mp3",
    bossCombat: "assets/sounds/music/forestOfTheBeasts-boss-combat.mp3",
  },
  palette: {
    bg: "#07110b",
    panel: "#102018",
    panel2: "#1a2d20",
    line: "#527449",
    gold: "#d6bd62",
    green: "#79c76c",
    floor: "#244a2f",
    floorAlt: "#1b3928",
    roomBg: "#09160e",
    roomBorder: "#6a8d50",
    tileBg: "#0d1c12",
    tileBgAlt: "#142819",
    hiddenTile: "#040905",
    wall: "#061008",
    wallLine: "rgba(188, 229, 141, 0.08)",
    wallDetail: "rgba(230, 198, 93, 0.12)",
    wallEdge: "rgba(107, 159, 84, 0.54)",
    door: "rgba(139, 112, 61, 0.48)",
    doorBorder: "rgba(224, 201, 120, 0.32)",
    doorOpen: "rgba(104, 190, 114, 0.4)",
    reachable: "rgba(121, 199, 108, 0.17)",
    reachableBorder: "rgba(202, 235, 126, 0.52)",
    reachableHover: "#315c36",
    pathPreview: "#446f3d",
    pathPreviewDot: "rgba(214, 189, 98, 0.3)",
    pathPreviewBorder: "rgba(231, 218, 132, 0.68)",
    objectBg: "rgba(5, 13, 7, 0.82)",
    objectBorder: "rgba(154, 194, 93, 0.52)",
    chestBg: "linear-gradient(145deg, #756632, #2d2514)",
    rockBg: "linear-gradient(145deg, #5d7356, #223525)",
    trapBg: "linear-gradient(145deg, #4d6a32, #172313)",
    portalBg: "radial-gradient(circle, #e0d16f, #3e8a51 55%, #071108)",
  },
  generator: {
    layout: "branching",
    roomCountByCategory: { 1: 10, 2: 20, 3: 21 },
    gridSize: 78,
    roomShapes: ["rectangle", "square", "l", "t"],
    roomWidth: { min: 6, max: 13 },
    roomHeight: { min: 6, max: 12 },
    squareSize: { min: 6, max: 9 },
    corridorLength: { min: 4, max: 9 },
    corridorWidth: 1,
    corridorStyle: "random-bend",
    extraConnectionRatio: 0.4,
    roomPadding: 2,
    corridorPadding: 1,
  },
  monsterTagGroups: [
    ["plant", "jungle"],
    ["plant", "forest"],
    ["beast", "forest"],
    ["beast", "swamp"],
    ["elemental", "water"],
    ["elemental", "earth"],
    ["elemental", "air"],
  ],
  bossMonsterTagGroups: [
    ["plant", "jungle", "boss"],
    ["plant", "forest", "boss"],
    ["beast", "forest", "boss"],
    ["beast", "swamp", "boss"],
    ["elemental", "water", "boss"],
    ["elemental", "earth", "boss"],
    ["elemental", "air", "boss"],
  ],
  furnitureTagGroups: [
    ["forest"],
    ["wilds"],
    ["swamp"],
    ["bog"],
    ["rock"],
    ["chest"],
  ],
  resourceNodeTagGroups: [
    ["resource-node", "plant"],
    ["resource-node", "forest"],
    ["resource-node", "wilds"],
    ["resource-node", "swamp"],
    ["resource-node", "bog"],
    ["resource-node", "wood"],
    ["resource-node", "stone"],
  ],
  terrainFloorIds: ["water-floor", "acid-floor", "healing-pool-floor"],
  terrainFloorWeights: {
    "water-floor": 5.5,
    "acid-floor": 0.8,
    "healing-pool-floor": 0.35,
  },
  terrainFloors: {
    pools: { min: 2, max: 4, chance: 1 },
    tilesPerPool: { min: 3, max: 6 },
    tileOverrides: {
      "acid-floor": { min: 2, max: 4 },
      "healing-pool-floor": { min: 2, max: 3 },
    },
    hallwayChance: 0.06,
    doorChance: 0.035,
  },
  furnitureSpawnChances: {
    chest: 0.08,
    "sunken-chest": 0.045,
    "large-tree": 0.14,
    "ancient-tree": 0.08,
    "hollow-tree": 0.075,
    "fallen-log": 0.09,
    "fungus-rotted-log": 0.06,
    bush: 0.1,
    "berry-bush": 0.055,
    "thorn-bush": 0.07,
    "dense-bramble": 0.09,
    "hanging-vines": 0.11,
    "root-cluster": 0.095,
    "mossy-boulder": 0.075,
    "hanging-moss": 0.08,
    "poison-flower": 0.065,
    "poison-ivy-patch": 0.06,
    "medicinal-herb-patch": 0.055,
    "mushroom-ring": 0.045,
    "animal-burrow": 0.04,
    "bird-nest": 0.04,
    "wasp-nest": 0.035,
    "bog-pool": 0.06,
    "deep-mud": 0.055,
    "giant-lily-pad": 0.045,
    "mangrove-root-wall": 0.055,
    "shallow-stream": 0.055,
  },
  trapTagGroups: [
    ["trap", "forest"],
    ["trap", "swamp"],
  ],
  traps: {
    roomChance: 0.24,
    corridorChance: 0.03,
    chestChance: 0.28,
  },
  resourceNodes: {
    min: 2,
    max: 4,
    chance: 1,
  },
  lootTableIds: ["basicDungeon", "magicForestItems"],
});
})();
