(() => {
window.DungeonContent.register("themes", "underwater", {
  name: "Underwater",
  description: "Aquatic beasts, sharks, currents, brine elementals, drowned ruins, sunken crates, reefs, and flooded hazards.",
  music: {
    exploration: "assets/sounds/music/crucibleOfTides-exploration.mp3",
    combat: "assets/sounds/music/crucibleOfTides-combat.mp3",
    bossCombat: "assets/sounds/music/crucibleOfTides-boss-combat.mp3",
  },
  palette: {
    bg: "#051014",
    panel: "#0b1a20",
    panel2: "#12303a",
    line: "#2e7e8f",
    gold: "#c7d48a",
    green: "#76d6bd",
    floor: "#1d5b69",
    floorAlt: "#174755",
    roomBg: "#061820",
    roomBorder: "#3fa2b8",
    tileBg: "#08202a",
    tileBgAlt: "#0f2d38",
    hiddenTile: "#02080b",
    wall: "#050d11",
    wallLine: "rgba(141, 238, 246, 0.08)",
    wallDetail: "rgba(199, 212, 138, 0.1)",
    wallEdge: "rgba(78, 192, 209, 0.52)",
    door: "rgba(62, 159, 178, 0.47)",
    doorBorder: "rgba(179, 243, 244, 0.3)",
    doorOpen: "rgba(118, 214, 189, 0.36)",
    reachable: "rgba(90, 207, 226, 0.17)",
    reachableBorder: "rgba(139, 231, 239, 0.5)",
    reachableHover: "#1b5663",
    pathPreview: "#266a7a",
    pathPreviewDot: "rgba(199, 212, 138, 0.28)",
    pathPreviewBorder: "rgba(225, 235, 158, 0.64)",
    objectBg: "rgba(4, 13, 17, 0.8)",
    objectBorder: "rgba(92, 218, 232, 0.5)",
    chestBg: "linear-gradient(145deg, #3c686f, #11262d)",
    rockBg: "linear-gradient(145deg, #456b70, #14282e)",
    trapBg: "linear-gradient(145deg, #286b78, #0b1920)",
    portalBg: "radial-gradient(circle, #dcfbff, #3ab5d9 52%, #061322)",
  },
  generator: {
    layout: "branching",
    roomCountByCategory: { 1: 10, 2: 20, 3: 20 },
    gridSize: 80,
    roomShapes: ["rectangle", "square", "l", "t"],
    roomWidth: { min: 5, max: 13 },
    roomHeight: { min: 5, max: 11 },
    squareSize: { min: 5, max: 9 },
    corridorLength: { min: 4, max: 9 },
    corridorWidth: 1,
    corridorStyle: "random-bend",
    extraConnectionRatio: 0.45,
    roomPadding: 2,
    corridorPadding: 1,
  },
  monsterTagGroups: [
    ["beast", "aquatic"],
    ["beast", "water"],
    ["elemental", "water"],
    ["undead", "zombie"],
  ],
  bossMonsterTagGroups: [
    ["beast", "aquatic", "boss"],
    ["beast", "water", "boss"],
    ["elemental", "water", "boss"],
    ["undead", "zombie", "boss"],
  ],
  furnitureTagGroups: [
    ["underwater"],
    ["swamp"],
    ["bog"],
    ["underdark", "cave"],
    ["chest"],
  ],
  resourceNodeTagGroups: [
    ["resource-node", "cave"],
    ["resource-node", "gem"],
    ["resource-node", "stone"],
    ["resource-node", "plant"],
  ],
  terrainFloorIds: ["tidal-current-floor", "water-floor", "healing-pool-floor", "acid-floor"],
  terrainFloorWeights: {
    "tidal-current-floor": 5,
    "water-floor": 4,
    "healing-pool-floor": 0.35,
    "acid-floor": 0.35,
  },
  terrainFloors: {
    pools: { min: 3, max: 6, chance: 1 },
    tilesPerPool: { min: 4, max: 7 },
    tileOverrides: {
      "healing-pool-floor": { min: 2, max: 3 },
      "acid-floor": { min: 2, max: 4 },
    },
    hallwayChance: 0.09,
    doorChance: 0.055,
  },
  furnitureSpawnChances: {
    "coral-growth": 0.085,
    "kelp-forest": 0.09,
    "shipwreck-planks": 0.06,
    "air-bubble-vent": 0.04,
    chest: 0.065,
    "iron-banded-chest": 0.04,
    "sunken-chest": 0.075,
    "soggy-crate": 0.075,
    "underground-pool": 0.09,
    "blackwater-spring": 0.065,
    "bog-pool": 0.075,
    "reed-cluster": 0.055,
    "floating-corpse": 0.04,
    "giant-lily-pad": 0.04,
    "stalagmite": 0.055,
    "crystal-growth": 0.05,
    "mineral-vein": 0.045,
    "narrow-rock-column": 0.055,
    "acid-pool": 0.035,
  },
  trapTagGroups: [
    ["trap", "swamp"],
    ["trap", "underdark"],
  ],
  traps: {
    roomChance: 0.24,
    corridorChance: 0.034,
    chestChance: 0.3,
  },
  resourceNodes: {
    min: 1,
    max: 3,
    chance: 0.85,
  },
  lootTableIds: ["basicDungeon"],
});
})();
