(() => {
window.DungeonContent.register("themes", "urban", {
  name: "Urban",
  description: "City alleys, sewers, guardroom ruins, scavenging beasts, ambush clutter, crates, barricades, and hidden valuables.",
  music: {
    exploration: "assets/sounds/music/oldGuardroom-exploration.mp3",
    combat: "assets/sounds/music/oldGuardroom-combat.mp3",
    bossCombat: "assets/sounds/music/oldGuardroom-boss-combat.mp3",
  },
  palette: {
    bg: "#0d0e10",
    panel: "#191a1d",
    panel2: "#23252a",
    line: "#5e6269",
    gold: "#caa85c",
    green: "#7db78d",
    floor: "#44464b",
    floorAlt: "#36383d",
    roomBg: "#111215",
    roomBorder: "#747880",
    tileBg: "#15171b",
    tileBgAlt: "#1e2126",
    hiddenTile: "#07080a",
    wall: "#0b0c0e",
    wallLine: "rgba(223, 224, 217, 0.06)",
    wallDetail: "rgba(202, 168, 92, 0.1)",
    wallEdge: "rgba(147, 151, 158, 0.45)",
    door: "rgba(163, 142, 96, 0.43)",
    doorBorder: "rgba(229, 209, 155, 0.28)",
    doorOpen: "rgba(125, 183, 141, 0.34)",
    reachable: "rgba(202, 168, 92, 0.16)",
    reachableBorder: "rgba(224, 193, 122, 0.48)",
    reachableHover: "#3e4247",
    pathPreview: "#555a60",
    pathPreviewDot: "rgba(125, 183, 141, 0.28)",
    pathPreviewBorder: "rgba(187, 225, 191, 0.64)",
    objectBg: "rgba(9, 10, 12, 0.8)",
    objectBorder: "rgba(170, 155, 117, 0.48)",
    chestBg: "linear-gradient(145deg, #76613a, #32281a)",
    rockBg: "linear-gradient(145deg, #696d70, #292d30)",
    trapBg: "linear-gradient(145deg, #5a5d62, #191b1f)",
    portalBg: "radial-gradient(circle, #e8d08a, #67727c 55%, #111218)",
  },
  generator: {
    layout: "branching",
    roomCountByCategory: { 1: 10, 2: 20, 3: 20 },
    gridSize: 74,
    roomShapes: ["rectangle", "square", "l", "t"],
    roomWidth: { min: 5, max: 12 },
    roomHeight: { min: 5, max: 10 },
    squareSize: { min: 5, max: 8 },
    corridorLength: { min: 4, max: 8 },
    corridorWidth: 1,
    corridorStyle: "horizontal-first",
    extraConnectionRatio: 0.4,
    roomPadding: 2,
    corridorPadding: 1,
  },
  monsterTagGroups: [
    ["humanoid"],
    ["beast", "urban"],
    ["beast", "sewer"],
    ["undead", "skeletal", "old-guardroom"],
    ["undead", "zombie"],
  ],
  bossMonsterTagGroups: [
    ["humanoid", "boss"],
    ["beast", "urban", "boss"],
    ["beast", "sewer", "boss"],
    ["undead", "skeletal", "old-guardroom", "boss"],
    ["undead", "zombie", "boss"],
  ],
  furnitureTagGroups: [
    ["urban"],
    ["old-guardroom"],
    ["dungeon"],
    ["ruin"],
    ["chest"],
  ],
  resourceNodeTagGroups: [
    ["resource-node", "dungeon"],
    ["resource-node", "ruin"],
    ["resource-node", "stone"],
    ["resource-node", "building"],
  ],
  terrainFloorIds: ["water-floor", "acid-floor", "healing-pool-floor"],
  terrainFloorWeights: {
    "water-floor": 3.5,
    "acid-floor": 0.75,
    "healing-pool-floor": 0.25,
  },
  terrainFloors: {
    pools: { min: 1, max: 3, chance: 0.85 },
    tilesPerPool: { min: 3, max: 5 },
    tileOverrides: {
      "acid-floor": { min: 2, max: 4 },
      "healing-pool-floor": { min: 2, max: 3 },
    },
    hallwayChance: 0.055,
    doorChance: 0.035,
  },
  furnitureSpawnChances: {
    "market-stall-wreckage": 0.07,
    "sewer-grate": 0.065,
    "stacked-crates": 0.09,
    "street-lamp": 0.055,
    table: 0.18,
    chest: 0.14,
    "iron-banded-chest": 0.06,
    "barricade": 0.1,
    "weapon-rack": 0.07,
    "armor-stand": 0.045,
    "rubble-pile": 0.08,
    "collapsed-pillar": 0.06,
    "standing-pillar": 0.045,
    bookshelf: 0.05,
    "standing-lantern": 0.055,
    "wall-torch": 0.045,
    "ceiling-light": 0.035,
    "undead-crate": 0.02,
    "soggy-crate": 0.05,
    "shallow-stream": 0.04,
    "acid-pool": 0.03,
  },
  trapTagGroups: [
    ["trap", "dungeon"],
    ["trap", "old-guardroom"],
  ],
  traps: {
    roomChance: 0.26,
    corridorChance: 0.035,
    chestChance: 0.32,
  },
  resourceNodes: {
    min: 1,
    max: 3,
    chance: 0.8,
  },
  lootTableIds: ["basicDungeon", "magicUndeadItems"],
});
})();
