(() => {
const abilityChoice = (abilities) => ({ type: "ability", abilities, amount: 1 });
const skillChoice = (count, choices = null) => ({ type: "skills", count, choices });
const expertiseChoice = (count) => ({ type: "expertise", count });
const saveChoice = (abilities) => ({ type: "save", abilities });

const feats = [
  {
    id: "actor",
    name: "Actor",
    choices: [abilityChoice(["cha"])],
    skillProficiencies: ["deception", "performance"],
    description: "+1 CHA and social performance training.",
  },
  {
    id: "alert",
    name: "Alert",
    effects: { initiativeBonus: 5 },
    description: "+5 initiative and better ambush readiness.",
  },
  {
    id: "athlete",
    name: "Athlete",
    choices: [abilityChoice(["str", "dex"])],
    effects: { speedBonusFeet: 5 },
    description: "+1 STR or DEX and a small movement boost.",
  },
  {
    id: "chef",
    name: "Chef",
    choices: [abilityChoice(["con", "wis"])],
    toolProficiencies: ["cooks-utensils"],
    effects: { maxHpBonus: 2 },
    description: "+1 CON or WIS, cook's utensils, and a small endurance bump.",
  },
  {
    id: "crossbow-expert",
    name: "Crossbow Expert",
    flags: ["ignoreAdjacentRangedDisadvantage"],
    description: "Ranged weapon attacks no longer suffer from adjacent enemies.",
  },
  {
    id: "crusher",
    name: "Crusher",
    choices: [abilityChoice(["str", "con"])],
    flags: ["crusher"],
    description: "+1 STR or CON. Bludgeoning hits are better at moving enemies.",
  },
  {
    id: "defensive-duelist",
    name: "Defensive Duelist",
    prerequisite: { ability: "dex", min: 13 },
    abilities: [
      {
        id: "featDefensiveDuelist",
        name: "Defensive Duelist",
        resource: "reaction",
        refresh: "turn",
        uses: 1,
        description: "Reaction: ready a finesse guard, gaining AC until your next turn.",
        subclassEffect: { kind: "selfStatus", status: { id: "defensive-duelist", label: "Defensive Duelist", acBonus: { proficiencyMultiplier: 1 }, expiresAtStartOfTurn: true } },
      },
    ],
    description: "Reaction AC boost while wielding a finesse weapon.",
  },
  {
    id: "dual-wielder",
    name: "Dual Wielder",
    flags: ["dualWielder"],
    description: "+1 AC while holding two melee weapons; off-hand attacks allow non-light one-handed melee weapons.",
  },
  {
    id: "dungeon-delver",
    name: "Dungeon Delver",
    skillProficiencies: ["perception", "investigation"],
    effects: { saveBonus: 1 },
    description: "Better trap-spotting skills and a small save bonus.",
  },
  {
    id: "durable",
    name: "Durable",
    choices: [abilityChoice(["con"])],
    effects: { maxHpBonus: 2 },
    description: "+1 CON and sturdier recovery.",
  },
  {
    id: "eldritch-adept",
    name: "Eldritch Adept",
    prerequisite: { spellcasting: true },
    choices: [{ type: "invocation", count: 1 }],
    description: "Learn one eldritch invocation available in this game.",
  },
  {
    id: "elemental-adept",
    name: "Elemental Adept",
    prerequisite: { spellcasting: true },
    choices: [{ type: "damageType", property: "elementalAdeptTypes", choices: ["acid", "cold", "fire", "lightning", "thunder"] }],
    flags: ["elementalAdept"],
    description: "Choose an element; your spells with that damage ignore resistance.",
  },
  {
    id: "elven-accuracy",
    name: "Elven Accuracy",
    prerequisite: { species: ["elf", "half-elf"] },
    choices: [abilityChoice(["dex", "int", "wis", "cha"])],
    effects: { attackBonus: 1 },
    description: "+1 DEX, INT, WIS, or CHA and a small precision bonus.",
  },
  {
    id: "fey-touched",
    name: "Fey Touched",
    choices: [abilityChoice(["int", "wis", "cha"])],
    spells: ["misty-step", "bless"],
    description: "+1 mental ability, Misty Step, and Bless.",
  },
  {
    id: "fighting-initiate",
    name: "Fighting Initiate",
    choices: [{ type: "fightingStyle" }],
    description: "Learn one fighting style.",
  },
  {
    id: "gift-of-the-chromatic-dragon",
    name: "Gift of the Chromatic Dragon",
    abilities: [
      {
        id: "featChromaticInfusion",
        name: "Chromatic Infusion",
        resource: "bonusAction",
        refresh: "longRest",
        uses: 1,
        description: "Bonus action: empower your next hits with elemental damage.",
        subclassEffect: { kind: "selfStatus", status: { id: "chromatic-infusion", label: "Chromatic Infusion", damageBonus: 3, damageType: "elemental", durationRounds: 10 } },
      },
    ],
    description: "Once per long rest, add elemental force to your attacks.",
  },
  {
    id: "gift-of-the-gem-dragon",
    name: "Gift of the Gem Dragon",
    choices: [abilityChoice(["int", "wis", "cha"])],
    abilities: [
      {
        id: "featGemRebuke",
        name: "Gem Rebuke",
        resource: "reaction",
        refresh: "longRest",
        uses: 1,
        description: "Reaction: strike back with force damage against a selected enemy.",
        subclassEffect: { kind: "damageTarget", dice: { count: 2, sides: 8 }, damageType: "force", riderStatus: "hamstrung" },
      },
    ],
    description: "+1 mental ability and a forceful reaction.",
  },
  {
    id: "gift-of-the-metallic-dragon",
    name: "Gift of the Metallic Dragon",
    spells: ["cure-wounds"],
    abilities: [
      {
        id: "featMetallicWings",
        name: "Protective Wings",
        resource: "reaction",
        refresh: "longRest",
        uses: 1,
        description: "Reaction: manifest protective wings for AC until your next turn.",
        subclassEffect: { kind: "selfStatus", status: { id: "metallic-wings", label: "Protective Wings", acBonus: { proficiencyMultiplier: 1 }, expiresAtStartOfTurn: true } },
      },
    ],
    description: "Learn Cure Wounds and gain a protective reaction.",
  },
  {
    id: "grappler",
    name: "Grappler",
    prerequisite: { ability: "str", min: 13 },
    flags: ["grappler"],
    description: "Gain advantage-like pressure against creatures you grapple.",
  },
  {
    id: "great-weapon-master",
    name: "Great Weapon Master",
    effects: { damageBonus: 2 },
    flags: ["greatWeaponMaster"],
    description: "Heavy melee hits deal extra damage in this crawler adaptation.",
  },
  {
    id: "gunner",
    name: "Gunner",
    choices: [abilityChoice(["dex"])],
    flags: ["ignoreAdjacentRangedDisadvantage"],
    description: "+1 DEX and no adjacent-enemy penalty for ranged attacks.",
  },
  {
    id: "healer",
    name: "Healer",
    skillProficiencies: ["medicine"],
    abilities: [
      {
        id: "featHealer",
        name: "Healer",
        resource: "action",
        refresh: "shortRest",
        uses: 1,
        description: "Action: restore a nearby wounded ally.",
        subclassEffect: { kind: "allyStatus", target: "selfOrAlly", status: { id: "healer-feat", label: "Healer", tempHp: { base: 4, proficiencyMultiplier: 1, levelMultiplier: 1 }, durationRounds: 10 } },
      },
    ],
    description: "Medicine proficiency and a short-rest healing support action.",
  },
  {
    id: "heavily-armored",
    name: "Heavily Armored",
    prerequisite: { armorProficiency: "medium" },
    choices: [abilityChoice(["str"])],
    armorProficiencies: ["heavy"],
    description: "+1 STR and heavy armor proficiency.",
  },
  {
    id: "heavy-armor-master",
    name: "Heavy Armor Master",
    prerequisite: { armorProficiency: "heavy" },
    choices: [abilityChoice(["str"])],
    flags: ["heavyArmorMaster"],
    description: "+1 STR and reduce weapon damage while wearing heavy armor.",
  },
  {
    id: "infernal-constitution",
    name: "Infernal Constitution",
    prerequisite: { species: ["tiefling"] },
    choices: [abilityChoice(["con"])],
    effects: { resistances: ["cold", "poison"] },
    description: "+1 CON and resistance to cold and poison.",
  },
  {
    id: "inspiring-leader",
    name: "Inspiring Leader",
    prerequisite: { ability: "cha", min: 13 },
    abilities: [
      {
        id: "featInspiringLeader",
        name: "Inspiring Leader",
        resource: "action",
        refresh: "shortRest",
        uses: 1,
        description: "Action: grant the party temporary HP.",
        subclassEffect: { kind: "partyStatus", status: { id: "inspiring-leader", label: "Inspired", tempHp: { levelMultiplier: 1, ability: "cha", abilityMultiplier: 1, min: 1 }, durationRounds: 10 } },
      },
    ],
    description: "Give the active party temporary HP once per short rest.",
  },
  {
    id: "keen-mind",
    name: "Keen Mind",
    choices: [abilityChoice(["int"])],
    skillProficiencies: ["investigation"],
    description: "+1 INT and Investigation proficiency.",
  },
  {
    id: "lightly-armored",
    name: "Lightly Armored",
    choices: [abilityChoice(["str", "dex"])],
    armorProficiencies: ["light"],
    description: "+1 STR or DEX and light armor proficiency.",
  },
  {
    id: "linguist",
    name: "Linguist",
    choices: [abilityChoice(["int"])],
    skillProficiencies: ["history"],
    description: "+1 INT and extra lore training.",
  },
  {
    id: "lucky",
    name: "Lucky",
    abilities: [
      {
        id: "featLucky",
        name: "Lucky",
        resource: "none",
        refresh: "longRest",
        uses: 3,
        description: "Spend luck before an important roll: your next attack, save, or skill check gains +5.",
        subclassEffect: { kind: "selfStatus", status: { id: "lucky-feat", label: "Lucky", attackBonus: 5, saveBonus: 5, skillBonus: 5, expiresAtEndOfTurn: true } },
      },
    ],
    description: "Three luck boosts per long rest.",
  },
  {
    id: "magic-initiate",
    name: "Magic Initiate",
    spells: ["fire-bolt", "mage-hand", "magic-missile"],
    description: "Learn Fire Bolt, Mage Hand, and Magic Missile.",
  },
  {
    id: "martial-adept",
    name: "Martial Adept",
    choices: [{ type: "maneuvers", count: 2 }],
    extraResourcePoolUses: { superiority: 1 },
    description: "Learn two Battle Master maneuvers and gain one superiority die.",
  },
  {
    id: "medium-armor-master",
    name: "Medium Armor Master",
    prerequisite: { armorProficiency: "medium" },
    flags: ["mediumArmorMaster"],
    description: "Medium armor allows up to +3 DEX to AC.",
  },
  {
    id: "metamagic-adept",
    name: "Metamagic Adept",
    prerequisite: { spellcasting: true },
    choices: [{ type: "metamagic", count: 2 }],
    extraResourcePoolUses: { metamagic: 2 },
    description: "Learn two Metamagic options and gain two sorcery points.",
  },
  {
    id: "mobile",
    name: "Mobile",
    effects: { speedBonusFeet: 10 },
    flags: ["mobile"],
    description: "+10 ft speed and creatures you melee attack cannot make opportunity attacks against you this turn.",
  },
  {
    id: "moderately-armored",
    name: "Moderately Armored",
    prerequisite: { armorProficiency: "light" },
    choices: [abilityChoice(["str", "dex"])],
    armorProficiencies: ["medium", "shield"],
    description: "+1 STR or DEX, medium armor, and shields.",
  },
  {
    id: "observant",
    name: "Observant",
    choices: [abilityChoice(["int", "wis"])],
    skillProficiencies: ["perception", "investigation"],
    description: "+1 INT or WIS plus sharp Perception and Investigation.",
  },
  {
    id: "piercer",
    name: "Piercer",
    choices: [abilityChoice(["str", "dex"])],
    effects: { damageBonus: 1 },
    description: "+1 STR or DEX and slightly stronger piercing offense.",
  },
  {
    id: "poisoner",
    name: "Poisoner",
    toolProficiencies: ["poisoners-kit"],
    effects: { extraDamage: [{ count: 1, sides: 4, type: "poison" }] },
    description: "Poisoner's kit proficiency and a small poison damage rider.",
  },
  {
    id: "resilient",
    name: "Resilient",
    choices: [saveChoice(["str", "dex", "con", "int", "wis", "cha"])],
    description: "+1 to one ability and proficiency in that saving throw.",
  },
  {
    id: "savage-attacker",
    name: "Savage Attacker",
    effects: { damageBonus: 1 },
    description: "Melee weapon damage is a little more reliable.",
  },
  {
    id: "sentinel",
    name: "Sentinel",
    flags: ["sentinel"],
    description: "Opportunity attacks stop enemy movement.",
  },
  {
    id: "shadow-touched",
    name: "Shadow Touched",
    choices: [abilityChoice(["int", "wis", "cha"])],
    spells: ["invisibility", "inflict-wounds"],
    description: "+1 mental ability, Invisibility, and Inflict Wounds.",
  },
  {
    id: "sharpshooter",
    name: "Sharpshooter",
    effects: { attackBonus: 1, damageBonus: 1 },
    flags: ["sharpshooter"],
    description: "Ranged attacks are slightly more accurate and damaging in this crawler adaptation.",
  },
  {
    id: "skill-expert",
    name: "Skill Expert",
    choices: [abilityChoice(["str", "dex", "con", "int", "wis", "cha"]), skillChoice(1), expertiseChoice(1)],
    description: "+1 ability, one skill proficiency, and one expertise.",
  },
  {
    id: "skilled",
    name: "Skilled",
    choices: [skillChoice(3)],
    description: "Gain three skill proficiencies.",
  },
  {
    id: "slasher",
    name: "Slasher",
    choices: [abilityChoice(["str", "dex"])],
    effects: { damageBonus: 1 },
    description: "+1 STR or DEX and slightly stronger slashing offense.",
  },
  {
    id: "spell-sniper",
    name: "Spell Sniper",
    prerequisite: { spellcasting: true },
    spells: ["eldritch-blast"],
    effects: { attackBonus: 1 },
    description: "Learn Eldritch Blast and gain a small spell attack bonus.",
  },
  {
    id: "squat-nimbleness",
    name: "Squat Nimbleness",
    prerequisite: { species: ["dwarf", "halfling", "gnome", "kobold"] },
    choices: [abilityChoice(["str", "dex"])],
    skillProficiencies: ["acrobatics", "athletics"],
    effects: { speedBonusFeet: 5 },
    description: "+1 STR or DEX, speed, and mobility skills.",
  },
  {
    id: "tavern-brawler",
    name: "Tavern Brawler",
    choices: [abilityChoice(["str", "con"])],
    flags: ["tavernBrawler"],
    description: "+1 STR or CON and better unarmed brawling.",
  },
  {
    id: "telekinetic",
    name: "Telekinetic",
    choices: [abilityChoice(["int", "wis", "cha"])],
    spells: ["mage-hand"],
    abilities: [
      {
        id: "featTelekineticShove",
        name: "Telekinetic Shove",
        resource: "bonusAction",
        refresh: "turn",
        uses: 1,
        description: "Bonus action: shove the selected enemy with mental force.",
        subclassEffect: { kind: "damageTarget", dice: { count: 1, sides: 1 }, damageType: "force", riderStatus: "hamstrung" },
      },
    ],
    description: "+1 mental ability, Mage Hand, and a bonus-action shove.",
  },
  {
    id: "tough",
    name: "Tough",
    effects: { maxHpPerLevel: 2 },
    description: "+2 maximum HP per level.",
  },
  {
    id: "war-caster",
    name: "War Caster",
    prerequisite: { spellcasting: true },
    flags: ["warCaster"],
    description: "Better concentration saves.",
  },
  {
    id: "weapon-master",
    name: "Weapon Master",
    choices: [abilityChoice(["str", "dex"])],
    weaponProficiencies: ["simple", "martial"],
    description: "+1 STR or DEX and broad weapon proficiency.",
  },
  {
    id: "wood-elf-magic",
    name: "Wood Elf Magic",
    prerequisite: { species: ["elf"], subrace: ["wood-elf"] },
    spells: ["guidance", "longstrider", "pass-without-trace"],
    description: "Learn a druid cantrip and wood-elf utility magic.",
  },
];

for (const feat of feats) {
  window.DungeonContent.register("feats", feat.id, feat);
}
})();
